//! Check the selected engine configuration's scenario-owned kernel closure against what actually
//! exists under a kernels root -- an install's published `kernels/`
//! directory, or a dev checkout's `kernels/` if it has one.
//!
//! This is the "is anything missing" question `kernel_manifest.json` alone cannot answer, because
//! that manifest is generated by scanning a directory: an artifact that was never built just does
//! not appear in it. Scenario declarations are the other half -- the model-owned list of what
//! MUST be there, independent of what currently is.
//!
//! Deliberately observability-only: this prints a report and its exit code reflects whether
//! everything declared was found, but nothing upstream (npu.rs, install.sh) reads that exit code
//! yet. Wiring this into a hard gate is a separate, later decision -- see declared-kernel-set,
//! spec section 5 question 4.
//!
//!   cargo run -p npu-asr --bin verify_declared_kernels -- [<repo-root>] [<kernels-root>]
//!
//! repo-root defaults to the current directory; `--config` selects the served scenario graph.
//! kernels-root defaults to <repo-root>/kernels (PUBLISHED_KERNELS_DIR) -- pass the install's
//! kernels directory explicitly to check a deployed set instead of a dev checkout.
//!
//! Device-free: filesystem and hashing only, never opens the NPU.

use std::path::PathBuf;

use npu_asr::kernel_registry::{
    default_engine_config_path, load_declared_kernel_set_from_engine_config, verify_declared_kernel_set_from,
    DeclaredStatus, PUBLISHED_KERNELS_DIR,
};

pub fn run(argv: Vec<String>) {
    let mut config = None;
    let mut engine_root = None;
    let mut positional = Vec::new();
    let mut args = argv.into_iter().skip(1);
    while let Some(arg) = args.next() {
        if arg == "--config" {
            config = args.next().map(PathBuf::from);
            if config.is_none() {
                eprintln!("kernels-verify: --config needs an engine.toml path");
                std::process::exit(2);
            }
        } else if arg == "--engine-root" {
            engine_root = args.next().map(PathBuf::from);
            if engine_root.is_none() {
                eprintln!("kernels-verify: --engine-root needs a directory");
                std::process::exit(2);
            }
        } else { positional.push(arg); }
    }
    let mut positional = positional.into_iter();
    let repo_root = positional.next().map(PathBuf::from).unwrap_or_else(|| PathBuf::from("."));
    let kernels_root = positional.next().map(PathBuf::from).unwrap_or_else(|| repo_root.join(PUBLISHED_KERNELS_DIR));
    let config = config.unwrap_or_else(default_engine_config_path);
    let engine_root = engine_root.unwrap_or_else(|| repo_root.clone());

    let declared = match load_declared_kernel_set_from_engine_config(&repo_root, &engine_root, &config) {
        Ok(d) => d,
        Err(e) => {
            eprintln!(
                "[kernels-verify] could not resolve served kernel declarations from {}: {e}",
                config.display()
            );
            std::process::exit(2);
        }
    };

    // repo_root is known here, so the source-freshness check runs: without it a stale artifact
    // reports PRESENT, which is what let a two-day-old kernel ship.
    let report = verify_declared_kernel_set_from(&declared, &kernels_root, Some(&repo_root));
    let total = report.len();
    let mut missing = 0usize;
    let mut unverified = 0usize;
    let mut mismatched = 0usize;
    let mut stale = 0usize;
    let mut present = 0usize;

    for entry in &report {
        let (tag, detail) = match &entry.status {
            DeclaredStatus::Present => {
                present += 1;
                ("PRESENT", String::new())
            }
            DeclaredStatus::PresentUnverified => {
                unverified += 1;
                ("UNVERIFIED", " (file exists, no kernel_manifest.json to check it against)".to_string())
            }
            DeclaredStatus::HashMismatch(e) => {
                mismatched += 1;
                ("MISMATCH", format!(" ({e})"))
            }
            DeclaredStatus::StaleSource { recorded, current } => {
                stale += 1;
                let was = recorded.as_deref().unwrap_or("(none)");
                ("STALE-SRC", format!(" (built from kernel source {}, tree has {})",
                                      &was[..was.len().min(12)], &current[..current.len().min(12)]))
            }
            DeclaredStatus::Missing => {
                missing += 1;
                (" MISSING", String::new())
            }
        };
        println!("[verify-declared-kernels] {tag:>10}  {}/{}{detail}", entry.family, entry.stem);
    }

    println!(
        "[verify-declared-kernels] {total} declared: {present} present, {unverified} unverified, \
         {mismatched} hash-mismatched, {stale} stale-source, {missing} missing  (kernels root: {})",
        kernels_root.display()
    );

    // stale-source counts as a failure: the artifact is intact but was built from source the
    // tree no longer has, which is the case this binary previously reported as PRESENT.
    if missing > 0 || unverified > 0 || mismatched > 0 || stale > 0 {
        std::process::exit(1);
    }
}
