//! Gemma-3 decode block schedule as DATA (the run-any-model rail: a MODEL is a block schedule over a
//! parameterized brick vocabulary, not a hand-fused kernel).
//!
//! This is the single source of truth both sides agree on: the on-NPU fused ELF is generated by
//! `route_b_kernels/decode_fused/gen_gemma_decode.py` from exactly this op order, and the host per-token
//! driver ([`crate::npu`]) walks it. Keeping it in Rust (CPU-only, no XRT) lets us unit-test the graph
//! shape without a device. Verified against transformers `modeling_gemma3.py` (2026-07-17).

use crate::config::GemmaConfig;

/// A parameterized brick OP-TYPE (not a model kernel). The IRON generator maps each to an operator
/// instance; the vocabulary is intentionally small and shared across every transformer-decoder model.
#[derive(Debug, Clone, PartialEq)]
pub enum Brick {
    /// Weighted RMSNorm over `size` (body = d_model, or head_dim for q/k norm). Gemma stores `(1+w)`.
    RmsNorm { size: usize, label: &'static str },
    /// GEMV projection `[M,K]` (bias-free in Gemma). `label` names the weight (Wq/Wk/.../W_head).
    Gemv { m: usize, k: usize, label: &'static str },
    /// RoPE over `rows` heads x `head_dim`; `theta` selects the local/global angle table.
    Rope { rows: usize, head_dim: usize, theta: RopeTheta },
    /// Append the new K or V row to the per-layer KV cache at the runtime `kv_off` position.
    KvAppend { which: Kv },
    /// GQA broadcast: repeat the single KV head to `groups` query heads (correctness-first; the
    /// free-by-layout batch-stride-0 read is the follow-on optimization).
    GqaRepeat { which: Kv, groups: usize },
    /// Batched score GEMV `K @ q` per head, then scale by `query_pre_attn_scalar**-0.5`.
    AttnScores { heads: usize, seq: usize, head_dim: usize },
    /// Softmax over the causal width `sm_mask` (runtime). `windowed` local layers add a low-cutoff band.
    Softmax { heads: usize, seq: usize, windowed: bool },
    /// Per-head V transpose feeding the context GEMV.
    TransposeV { heads: usize, seq: usize, head_dim: usize },
    /// Batched context GEMV `V^T @ weights` per head.
    AttnContext { heads: usize, seq: usize, head_dim: usize },
    /// GeGLU activation: `gelu_tanh(gate)` then elementwise `* up` (Gemma uses GELU-tanh, not SiLU).
    Geglu { ff: usize },
    /// Residual `out = a + b` over d_model.
    Residual { size: usize },
}

/// Which cache stream a brick touches.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Kv {
    Key,
    Value,
}

/// RoPE angle table selector (Gemma-3 uses a different theta on local vs global layers).
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum RopeTheta {
    Local,
    Global,
}

/// Build the full per-token decode schedule for a Gemma config: `n_layers` transformer blocks then the
/// final norm + tied lm-head. `seq` is the KV-cache padded capacity (>= prompt + generated tokens).
///
/// Per block (all projections bias-free), in forward order:
///   input RMSNorm -> Q/K/V GEMV -> per-head q/k RMSNorm -> RoPE(theta) -> KV append -> GQA repeat ->
///   score GEMV -> softmax -> V transpose -> context GEMV -> O GEMV -> post-attn RMSNorm -> residual ->
///   pre-ffn RMSNorm -> gate/up GEMV -> GeGLU -> down GEMV -> post-ffn RMSNorm -> residual.
pub fn decode_schedule(cfg: &GemmaConfig, seq: usize) -> Vec<Brick> {
    let mut s = Vec::new();
    let qd = cfg.n_q_heads * cfg.head_dim;
    let kvd = cfg.n_kv_heads * cfg.head_dim;
    let group = cfg.gqa_group();
    for l in 0..cfg.n_layers {
        let theta = if cfg.is_global_layer(l) { RopeTheta::Global } else { RopeTheta::Local };
        let windowed = !cfg.is_global_layer(l);
        s.push(Brick::RmsNorm { size: cfg.d_model, label: "input" });
        s.push(Brick::Gemv { m: qd, k: cfg.d_model, label: "Wq" });
        s.push(Brick::Gemv { m: kvd, k: cfg.d_model, label: "Wk" });
        s.push(Brick::Gemv { m: kvd, k: cfg.d_model, label: "Wv" });
        s.push(Brick::RmsNorm { size: cfg.head_dim, label: "q_norm" });
        s.push(Brick::RmsNorm { size: cfg.head_dim, label: "k_norm" });
        s.push(Brick::Rope { rows: cfg.n_q_heads, head_dim: cfg.head_dim, theta });
        s.push(Brick::Rope { rows: cfg.n_kv_heads, head_dim: cfg.head_dim, theta });
        s.push(Brick::KvAppend { which: Kv::Key });
        s.push(Brick::KvAppend { which: Kv::Value });
        s.push(Brick::GqaRepeat { which: Kv::Key, groups: group });
        s.push(Brick::GqaRepeat { which: Kv::Value, groups: group });
        s.push(Brick::AttnScores { heads: cfg.n_q_heads, seq, head_dim: cfg.head_dim });
        s.push(Brick::Softmax { heads: cfg.n_q_heads, seq, windowed });
        s.push(Brick::TransposeV { heads: cfg.n_q_heads, seq, head_dim: cfg.head_dim });
        s.push(Brick::AttnContext { heads: cfg.n_q_heads, seq, head_dim: cfg.head_dim });
        s.push(Brick::Gemv { m: cfg.d_model, k: qd, label: "Wo" });
        s.push(Brick::RmsNorm { size: cfg.d_model, label: "post_attn" });
        s.push(Brick::Residual { size: cfg.d_model });
        s.push(Brick::RmsNorm { size: cfg.d_model, label: "pre_ffn" });
        s.push(Brick::Gemv { m: cfg.ffn_dim, k: cfg.d_model, label: "Wgate" });
        s.push(Brick::Gemv { m: cfg.ffn_dim, k: cfg.d_model, label: "Wup" });
        s.push(Brick::Geglu { ff: cfg.ffn_dim });
        s.push(Brick::Gemv { m: cfg.d_model, k: cfg.ffn_dim, label: "Wdown" });
        s.push(Brick::RmsNorm { size: cfg.d_model, label: "post_ffn" });
        s.push(Brick::Residual { size: cfg.d_model });
    }
    s.push(Brick::RmsNorm { size: cfg.d_model, label: "final" });
    s.push(Brick::Gemv { m: cfg.vocab, k: cfg.d_model, label: "W_head" });
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::GEMMA3_270M;

    #[test]
    fn schedule_shape() {
        let s = decode_schedule(&GEMMA3_270M, 2048);
        // 26 bricks per layer + 2 tail (final norm + lm-head).
        assert_eq!(s.len(), 26 * GEMMA3_270M.n_layers + 2);
        assert_eq!(s.last(), Some(&Brick::Gemv { m: 262144, k: 640, label: "W_head" }));
    }

    #[test]
    fn dual_theta_by_layer() {
        let s = decode_schedule(&GEMMA3_270M, 2048);
        // layer 0 is local (theta_local), layer 5 (0-based) is global.
        let ropes: Vec<_> = s.iter().filter_map(|b| match b {
            Brick::Rope { theta, .. } => Some(*theta),
            _ => None,
        }).collect();
        assert_eq!(ropes[0], RopeTheta::Local); // layer 0 q
        // layer 5 is global -> its first rope is the 5*2 = 10th rope entry (2 ropes/layer).
        assert_eq!(ropes[5 * 2], RopeTheta::Global);
    }

    #[test]
    fn tied_head_and_norm_count() {
        let s = decode_schedule(&GEMMA3_270M, 2048);
        // 6 RMSNorms per layer (input, q, k, post_attn, pre_ffn, post_ffn) + 1 final.
        let norms = s.iter().filter(|b| matches!(b, Brick::RmsNorm { .. })).count();
        assert_eq!(norms, 6 * GEMMA3_270M.n_layers + 1);
    }
}
