##===- Makefile.noinline_test -----------------------------------------===##
#
# A/B test: is __attribute__((noinline)) on relpos_mha.cc's exp2f_vec still
# load-bearing on the current Peano pin? Builds STEP=6 (relpos_rowtiled_bake,
# the exact "big fused 3-pass softmax loop" context the noinline comment names)
# from a verbatim copy of relpos_mha.cc (SRC=relpos_mha_with_noinline, the
# shipped default) or a copy with the attribute stripped
# (SRC=relpos_mha_no_noinline). Neither touches route_b_kernels/relpos_mha/.
#
# Usage: make -f Makefile.noinline_test NPU2=1 SRC=relpos_mha_with_noinline T=32 TQ=8
#        make -f Makefile.noinline_test NPU2=1 SRC=relpos_mha_no_noinline   T=32 TQ=8
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
##===--------------------------------------------------------------------===##

srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

include ${srcdir}/../../makefile-common

devicename ?= $(if $(filter 1,$(NPU2)),npu2,npu)
T ?= 32
TQ ?= 8
KB ?= 43
TACTIVE ?= ${T}
SRC ?= relpos_mha_with_noinline

targetname = relpos_rowtiled
aie_py_src = relpos_rowtiled_iron.py

ifeq ($(devicename),npu2)
VPATH :=${srcdir}/../../../aie_kernels/aie2p
else
VPATH :=${srcdir}/../../../aie_kernels/aie2
endif

.PHONY all: build_${SRC}/${targetname}.mlir build_${SRC}/final.xclbin

build_${SRC}/%.cc.o: %.cc
	mkdir -p ${@D}
ifeq ($(devicename),npu2)
	cd ${@D} && ${PEANO_INSTALL_DIR}/bin/clang++ ${PEANOWRAP2P_FLAGS} -DRELPOS_T=${T} -DRELPOS_TQ=${TQ} -DRELPOS_KB=${KB} -DRELPOS_TACTIVE=${TACTIVE} -c $< -o ${@F}
else
	echo "Only npu2 supported for this example"
endif

build_${SRC}/kernels.a: build_${SRC}/${SRC}.cc.o
	ar rvs $@ $+

build_${SRC}/${targetname}.mlir: ${srcdir}/${aie_py_src}
	mkdir -p ${@D}
	python3 $< -d ${devicename} -T ${T} > $@

build_${SRC}/final.xclbin: build_${SRC}/${targetname}.mlir build_${SRC}/kernels.a
	mkdir -p ${@D}
	cd ${@D} && aiecc --get-xclbin --get-npu-insts \
		    --xclbin-name=final.xclbin \
		    --no-xchesscc --no-xbridge \
		    --npu-insts-name=insts.bin $(<:%=../%)

clean:
	rm -rf build_relpos_mha_with_noinline build_relpos_mha_no_noinline
