#!/usr/bin/env python3
"""Host numpy golden for route_b_kernels/bricks/sin/sin.cc.

The kernel computes sin(x) for unbounded f32 x as: range-reduce to r = x - 2*pi*round(x/(2*pi))
so r in [-pi, pi], then evaluate via aie::linear_approx over a bfloat16 LUT of one period.
Primitive choice is measured, not assumed: linear_approx beats parallel_lookup on sin by 3.5x at
512 B and 65x at 8 KB at matched memory (kb/lut-primitive-choice-lookup-vs-linear-approx).

`sin_lut_emulated` below is a bit-faithful transcription of what the DEVICE does, including the
bfloat16 narrowing of the reduced argument and the piecewise-linear interpolation. It is the
prediction the device gate is checked against; `np.sin` is the ground truth both are measured on.

Usage: python3 golden.py    # prints max abs err of the emulation vs np.sin, and emits the .inc
"""
import numpy as np

TWO_PI = 2.0 * np.pi
LUT_ENTRIES = 256          # 256 * 24 B = 6 KB, inside the 8 KB budget the KB note measures
LUT_LO = -np.pi
LUT_HI = np.pi
STEP = (LUT_HI - LUT_LO) / LUT_ENTRIES


def bf16(x):
    """Round f32 -> bfloat16 -> f32, round-to-nearest-even (what the device does on narrowing)."""
    u = np.ascontiguousarray(x, dtype=np.float32).view(np.uint32).astype(np.uint32)
    lsb = (u >> 16) & 1
    rounded = ((u + 0x7FFF + lsb) & 0xFFFF0000).astype(np.uint32)
    return rounded.view(np.float32)


def range_reduce(x):
    """r = x - 2*pi*round(x / 2*pi), giving r in [-pi, pi]."""
    x = np.asarray(x, dtype=np.float32)
    k = np.rint(x / TWO_PI)
    return (x - TWO_PI * k).astype(np.float32)


def sin_ref(x):
    """Ground truth."""
    return np.sin(np.asarray(x, dtype=np.float64)).astype(np.float32)


def lut_tables():
    """(offset, slope) per entry: value at the left edge and the slope across the cell."""
    edges = LUT_LO + STEP * np.arange(LUT_ENTRIES + 1, dtype=np.float64)
    vals = np.sin(edges)
    offset = vals[:-1].astype(np.float32)
    slope = ((vals[1:] - vals[:-1]) / STEP).astype(np.float32)
    return offset, slope


def sin_lut_emulated(x):
    """Bit-faithful emulation of the device path: reduce, narrow to bf16, interpolate."""
    r = range_reduce(x)
    r_b = bf16(r)
    offset, slope = lut_tables()
    idx = np.clip(((r_b - LUT_LO) / STEP).astype(np.int32), 0, LUT_ENTRIES - 1)
    frac = (r_b - (LUT_LO + idx * STEP)).astype(np.float32)
    # linear_approx narrows the table to bfloat16 and accumulates in f32
    return (bf16(offset[idx]) + bf16(slope[idx]) * frac).astype(np.float32)


def rel_l2(a, b):
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    num = np.linalg.norm((a - b).ravel())
    den = np.linalg.norm(b.ravel())
    return float(num / den) if den > 0 else float(num)


def emit_inc(path):
    """Emit the aie::lut<4,bfloat16> ab/cd tables. 4 copies, 128-bit-bank interleaved.

    Layout follows bricks/rope-lut/rope_lut_tables.inc; the bank-granularity rationale is in
    log/2026-07/2026-07-25-rope-lut-root-cause-bank-granularity.md. ab holds (offset,slope) pairs for
    even entries, cd for odd, each replicated 4x.
    """
    offset, slope = lut_tables()
    def fmt(vals):
        return ",\n  ".join(", ".join(f"{v:.8e}f" for v in vals[i:i + 8]) for i in range(0, len(vals), 8))
    inter_ab, inter_cd = [], []
    for i in range(LUT_ENTRIES):
        (inter_ab if i % 2 == 0 else inter_cd).extend([offset[i], slope[i]])
    body = f"""// AUTO-GENERATED by bricks/sin/golden.py -- do not hand-edit.
// aie::lut<4,bfloat16> tables for sin over [{LUT_LO:.8f}, {LUT_HI:.8f}), {LUT_ENTRIES} entries.
#pragma once
static const float kSinApproxAb[] = {{
  {fmt(inter_ab * 4)}
}};
static const float kSinApproxCd[] = {{
  {fmt(inter_cd * 4)}
}};
static constexpr int kSinLutEntries = {LUT_ENTRIES};
static constexpr float kSinLutLo = {LUT_LO:.8f}f;
static constexpr float kSinLutStep = {STEP:.10f}f;
"""
    path.write_text(body)


if __name__ == "__main__":
    from pathlib import Path
    rng = np.random.default_rng(0)
    # Snake's argument is alpha*x: alpha is a learned per-channel scale, x a post-conv activation.
    # Cover +/-64 (about 10 periods) so range reduction is actually exercised.
    x = (rng.random(1 << 16, dtype=np.float32) * 128.0 - 64.0).astype(np.float32)
    got = sin_lut_emulated(x)
    ref = sin_ref(x)
    print("max abs err:", float(np.max(np.abs(got - ref))))
    print("rel-L2     :", rel_l2(got, ref))
    assert rel_l2(got, ref) <= 3e-2, "emulated LUT path misses the brick gate"
    emit_inc(Path(__file__).parent / "sin_lut_tables.inc")
    print("wrote sin_lut_tables.inc")
