//! Gate: `gemma4_media.rs`'s host towers against the real HF oracle (transformers 5.17.0), wired
//! from the SAME checkpoint the served model uses (`gemma4-12b-qat/checkpoint`), generated by
//! `scripts/gemma4_resize_oracle_gen.py` at an image size that makes the aspect-ratio-preserving
//! resize a REAL resize -- 1200x1600 -> 672x912 -- rather than the no-op
//! `gemma4_towers_oracle_gen.py` tests elsewhere in this repo.
//!
//! Requires the oracle dir to exist (regenerate with the command in that script's docstring); if
//! it does not, these tests are skipped with a loud message rather than silently passing.

use ndarray::ArrayD;
use ndarray_npy::read_npy;
use npu_engine::llm::gemma4_media::{self, Gemma4Towers};
use std::path::{Path, PathBuf};

const GATE: f64 = 1e-4;

fn checkpoint_dir() -> PathBuf { PathBuf::from("/mnt/data/xdna/artifacts/gemma4-12b-qat/checkpoint") }
fn oracle_dir() -> PathBuf { PathBuf::from("/mnt/data/xdna/artifacts/gemma4-12b-qat/resize_oracle") }
fn upscale_oracle_dir() -> PathBuf {
    PathBuf::from("/mnt/data/xdna/artifacts/gemma4-12b-qat/resize_oracle_upscale")
}

fn skip_if_missing(p: &Path) -> bool {
    if !p.exists() {
        eprintln!("SKIP: {} not present (regenerate via scripts/gemma4_resize_oracle_gen.py)", p.display());
        true
    } else { false }
}

fn rel_l2(a: &[f32], b: &[f32]) -> f64 {
    let (mut num, mut den) = (0.0f64, 0.0f64);
    for (x, y) in a.iter().zip(b) {
        num += ((*x as f64) - (*y as f64)).powi(2);
        den += (*y as f64).powi(2);
    }
    (num.sqrt()) / (den.sqrt() + 1e-30)
}

fn load_npy_f32(path: &Path) -> Vec<f32> {
    let a: ArrayD<f32> = read_npy(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    a.iter().copied().collect()
}
fn load_npy_shape(path: &Path) -> Vec<usize> {
    let a: ArrayD<f32> = read_npy(path).unwrap();
    a.shape().to_vec()
}

/// Isolates the resize stage alone: decode the oracle's pre-resize tensor, resize with our Rust
/// uint8 fixed-point port, compare directly to torchvision's `tvF.resize(..., antialias=True)`
/// output. Runs against both a downscale fixture (1200x1600 -> 672x912) and an upscale one
/// (100x140 -> 672x912, HF's budget upsamples small images too) since the antialias filter support
/// differs between the two regimes.
fn resize_stage_case(dir: &Path) {
    if skip_if_missing(dir) { return; }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join("meta.json")).unwrap()).unwrap();
    let (in_h, in_w) = (meta["image_hw_in"][0].as_u64().unwrap() as usize,
                        meta["image_hw_in"][1].as_u64().unwrap() as usize);
    let (out_h, out_w) = (meta["image_hw_resized"][0].as_u64().unwrap() as usize,
                          meta["image_hw_resized"][1].as_u64().unwrap() as usize);

    let input = load_npy_f32(&dir.join("prep_image_input.npy")); // (3,in_h,in_w) f32-cast-of-uint8
    let chw: Vec<Vec<Vec<f32>>> = (0..3).map(|c| (0..in_h).map(|y| {
        let base = (c * in_h + y) * in_w;
        input[base..base + in_w].to_vec()
    }).collect()).collect();

    let resized = gemma4_media::resize_for_gate(&chw, in_h, in_w, out_h, out_w);
    let mine: Vec<f32> = resized.iter().flat_map(|p| p.iter().flat_map(|r| r.iter().copied())).collect();
    let oracle = load_npy_f32(&dir.join("prep_image_resized.npy"));
    assert_eq!(mine.len(), oracle.len());
    let err = rel_l2(&mine, &oracle);
    eprintln!("resize stage ({}) rel-L2 = {err:.3e} (gate {GATE:.0e})", dir.display());
    assert!(err <= GATE, "resize stage rel-L2 {err:.3e} exceeds gate {GATE:.0e} ({})", dir.display());
}

#[test]
fn resize_stage_rel_l2_against_torchvision_bicubic_antialias_downscale() {
    resize_stage_case(&oracle_dir());
}

#[test]
fn resize_stage_rel_l2_against_torchvision_bicubic_antialias_upscale() {
    resize_stage_case(&upscale_oracle_dir());
}

/// Full vision pipeline (PNG decode -> resize -> rescale -> patchify -> merge -> pad -> tower ->
/// drop padding), against the oracle's real-checkpoint tower output, real PNG bytes both sides.
#[test]
fn vision_forward_end_to_end_against_oracle() {
    let dir = oracle_dir();
    if skip_if_missing(&dir) { return; }
    if skip_if_missing(&checkpoint_dir()) { return; }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join("meta.json")).unwrap()).unwrap();
    let n_real = meta["n_real_soft_tokens"].as_u64().unwrap() as usize;
    let max_soft_tokens = meta["num_soft_tokens"].as_u64().unwrap() as usize;

    let towers = Gemma4Towers::load(&checkpoint_dir()).unwrap();
    let png = std::fs::read(dir.join("input_image.png")).unwrap();
    let rows = towers.vision_forward(&png, max_soft_tokens).unwrap();
    assert_eq!(rows.len(), n_real, "dropped-padding row count must match the oracle's n_real");

    let oracle_shape = load_npy_shape(&dir.join("vis_s7_projection.npy")); // [1, max_soft_tokens, d]
    let d_model = oracle_shape[2];
    let oracle = load_npy_f32(&dir.join("vis_s7_projection.npy"));
    let mine: Vec<f32> = rows.iter().flatten().copied().collect();
    let oracle_real: Vec<f32> = oracle[..n_real * d_model].to_vec();
    let err = rel_l2(&mine, &oracle_real);
    eprintln!("vision_forward end-to-end rel-L2 = {err:.3e} (gate {GATE:.0e}), n_real={n_real}");
    assert!(err <= GATE, "vision_forward rel-L2 {err:.3e} exceeds gate {GATE:.0e}");
}

/// Audio pipeline (WAV decode -> frame -> tower), against the oracle.
#[test]
fn audio_forward_end_to_end_against_oracle() {
    let dir = oracle_dir();
    if skip_if_missing(&dir) { return; }
    if skip_if_missing(&checkpoint_dir()) { return; }
    let aud_path = dir.join("aud_projection.npy");
    if skip_if_missing(&aud_path) { return; }

    let towers = Gemma4Towers::load(&checkpoint_dir()).unwrap();
    let wav = std::fs::read("/mnt/data/xdna/artifacts/wer_clips_large/en_044.wav").unwrap();
    let rows = towers.audio_forward(&wav).unwrap();

    let oracle = load_npy_f32(&aud_path);
    let mine: Vec<f32> = rows.iter().flatten().copied().collect();
    assert_eq!(mine.len(), oracle.len(), "audio token count must match the oracle's");
    let err = rel_l2(&mine, &oracle);
    eprintln!("audio_forward end-to-end rel-L2 = {err:.3e} (gate {GATE:.0e})");
    assert!(err <= GATE, "audio_forward rel-L2 {err:.3e} exceeds gate {GATE:.0e}");
}

/// Known-bad control: the vision gate must actually be capable of FAILING, not just of passing on
/// whatever we feed it. Compares the oracle's real output against a deliberately WRONG merge
/// ordering (row-reversed) of our own output -- proves `rel_l2` and the gate threshold reject a
/// real mismatch rather than being vacuously satisfied by, say, comparing a vector to itself under
/// a broken norm.
#[test]
fn known_bad_control_a_shuffled_output_fails_the_gate() {
    let dir = oracle_dir();
    if skip_if_missing(&dir) { return; }
    if skip_if_missing(&checkpoint_dir()) { return; }
    let meta: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join("meta.json")).unwrap()).unwrap();
    let n_real = meta["n_real_soft_tokens"].as_u64().unwrap() as usize;
    let max_soft_tokens = meta["num_soft_tokens"].as_u64().unwrap() as usize;

    let towers = Gemma4Towers::load(&checkpoint_dir()).unwrap();
    let png = std::fs::read(dir.join("input_image.png")).unwrap();
    let mut rows = towers.vision_forward(&png, max_soft_tokens).unwrap();
    rows.reverse(); // known-bad: wrong row order

    let oracle_shape = load_npy_shape(&dir.join("vis_s7_projection.npy"));
    let d_model = oracle_shape[2];
    let oracle = load_npy_f32(&dir.join("vis_s7_projection.npy"));
    let oracle_real: Vec<f32> = oracle[..n_real * d_model].to_vec();
    let mine: Vec<f32> = rows.iter().flatten().copied().collect();
    let err = rel_l2(&mine, &oracle_real);
    eprintln!("known-bad (reversed rows) rel-L2 = {err:.3e}");
    assert!(err > GATE, "a shuffled output must fail the gate, got rel-L2={err:.3e}");
}
