#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""T3.2 oracle: measure what the shipped decode graph's missing sliding-window mask actually costs.

llm_decode_spec.py's GEMMA4_12B carries sliding_window=1024, sw_pattern=6, but gen_llm_decode.py
applies one scalar causal width (`sm_mask`) to every layer -- so past n_past=1024, all 40 sliding
layers compute full causal attention instead of windowed. scripts/gate_llm_reference.py's numpy
backend REFUSES a spec with sliding_window set (line 82) rather than compute it wrong, so nothing
in this repo can see the bug.

This is the oracle that can see it. Rather than hand-derive Gemma-4's forward pass in numpy --
sandwich norms, dual-theta partial-rotary RoPE, a gainless v_norm, a per-layer trained
`layer_scalar` applied to the WHOLE block output (`hidden_states *= self.layer_scalar`,
modeling_gemma4_unified.py:524) -- this runs the checkpoint's OWN modeling code, correct by
construction.

TWO PARALLEL, PERSISTENT trajectories, not a mask patch around one snapshot: transformers'
`DynamicCache(config=...)` builds a `DynamicSlidingWindowLayer` per sliding layer that PHYSICALLY
truncates its stored K/V to the last `sliding_window-1` tokens on every `update()`
(cache_utils.py, DynamicSlidingWindowLayer.update). A mask-only counterfactual computed from a
snapshot of the CORRECT cache therefore sees nothing to un-evict -- confirmed empirically first
(rel-L2 exactly 0.0 at n_past=2047 against a same-cache snapshot). So "correct" and "buggy" each
keep their OWN cache from position 0: correct's is config-native (sliding_window=1024, evicts);
buggy's has sliding_window patched huge from the start (never evicts) -- exactly today's shipped
engine, whose KV buffer is sized to max_seq and never drops anything. Both are fed the SAME next
token (the correct branch's own greedy pick) every step, so the two trajectories differ only in
what each layer's attention can see, never in which tokens were generated by which branch.

MEMORY: one truncated model, two caches (a `DynamicSlidingWindowLayer`'s footprint is capped at
`sliding_window` regardless of n_past; the buggy cache grows to `max_pos`, still small at L<=12).
Real weights come off local disk via safetensors mmap (`low_cpu_mem_usage=True`), not `np.load`.
Run under scripts/jobq.sh, capped to the coordinator's own number (6-of-48 layers = 3.35 GB
resident) plus headroom.

Needs a transformers build with Gemma4UnifiedConfig -- this repo's pinned .venv-export (4.57.6)
predates Gemma-4 support upstream:
    python3 -m venv /path/.venv-hfref && /path/.venv-hfref/bin/pip install torch \\
        --index-url https://download.pytorch.org/whl/cpu && \\
        /path/.venv-hfref/bin/pip install "transformers>=4.58" accelerate

    HF_HOME=/mnt/data/cache/huggingface HF_HUB_OFFLINE=1 scripts/jobq.sh --mem 8G --class build -- \\
        /path/.venv-hfref/bin/python designs/decode_fused/probe_sliding_window_divergence.py
"""
import argparse
import json
import os


def rel_l2(a, b):
    a, b = a.float(), b.float()
    denom = a.norm().item()
    return (a - b).norm().item() / denom if denom else float(b.norm().item() != 0)


def run_step(model, cache, next_tok, sliding_window, capture_layers):
    """One forward step of one branch, at an explicit `sliding_window` value. `capture_layers`
    (possibly empty) are hooked to record each self_attn module's output (post-o_proj, pre-
    residual) -- cheap, so only paid at the positions being measured.
    """
    import torch

    text_cfg = model.model.language_model.config
    text_cfg.sliding_window = sliding_window
    hooks, captured = [], {}
    for i in capture_layers:
        def mk(i):
            def h(_mod, _inp, out):
                captured[i] = out[0].detach().clone()
            return h
        hooks.append(model.model.language_model.layers[i].self_attn.register_forward_hook(mk(i)))
    try:
        with torch.no_grad():
            out = model(input_ids=torch.tensor([[next_tok]]), past_key_values=cache, use_cache=True)
    finally:
        for h in hooks:
            h.remove()
    return out.logits[0, -1].detach().clone(), out.past_key_values, captured


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="unsloth/gemma-4-12b-it")
    ap.add_argument("--layers", type=int, default=6,
                    help="truncated depth -- 6 gives 5 sliding + 1 global (layer 5), the minimal "
                         "pair per sw_pattern=6. Matches tests/refs/gemma4-12b/bf16_oracle_l6.json")
    ap.add_argument("--prompt", default="The capital of France is")
    ap.add_argument("--validate-ref", default="tests/refs/gemma4-12b/bf16_oracle_l6.json",
                    help="cross-check the first `validate_steps` free-run tokens against this "
                         "already-recorded real-weight oracle before trusting the harness")
    ap.add_argument("--validate-steps", type=int, default=8)
    ap.add_argument("--window", type=int, default=None,
                    help="override sliding_window (default: the checkpoint's real 1024) -- for a "
                         "fast mechanism check at a small window, not for the real measurement")
    ap.add_argument("--targets", default="500,1024,1536,2047",
                    help="n_past values to probe, scaled with --window if given (see main())")
    ap.add_argument("--capture-layers", default="0,5",
                    help="layer indices to hook for attention-output rel-L2 (sliding, global)")
    ap.add_argument("--out", default=None, help="write the full JSON report here")
    a = ap.parse_args()

    import torch
    from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer

    os.environ.setdefault("HF_HUB_OFFLINE", "1")
    targets = sorted(int(x) for x in a.targets.split(","))
    capture_layers = [int(x) for x in a.capture_layers.split(",")]

    cfg = AutoConfig.from_pretrained(a.model)
    cfg.vision_config = None  # skip building/loading the vision and audio towers entirely --
    cfg.audio_config = None   # Gemma4UnifiedModel.__init__ only constructs them when non-None
    tc = cfg.get_text_config()
    tc.num_hidden_layers = a.layers
    tc.layer_types = list(tc.layer_types)[: a.layers]
    tc.final_logit_softcapping = None  # avoids the documented cap-saturation degeneracy at
    # truncated depth (llm_hf_bf16_ref.py: pre-cap ~1168 vs cap 30 -> argmax becomes index order)
    real_window = a.window if a.window is not None else tc.sliding_window
    assert tc.sliding_window == 1024 or a.window is not None, \
        f"expected sliding_window=1024, got {tc.sliding_window}"
    print(f"[probe] layer_types: {tc.layer_types}  (global at "
          f"{[i for i, t in enumerate(tc.layer_types) if t == 'full_attention']}), "
          f"window={real_window}")

    tok = AutoTokenizer.from_pretrained(a.model)
    model = AutoModelForCausalLM.from_pretrained(
        a.model, config=cfg, dtype=torch.bfloat16, attn_implementation="eager",
        low_cpu_mem_usage=True).eval()

    prompt_ids = tok(a.prompt, return_tensors="pt").input_ids[0].tolist()
    print(f"[probe] prompt_ids: {prompt_ids}")

    ref = None
    if a.window is None and a.validate_ref and os.path.isfile(a.validate_ref):
        ref = json.load(open(a.validate_ref))
        assert ref["prompt_ids"] == prompt_ids, "tokenizer disagrees with the recorded reference"
        assert ref["layers"] == a.layers and ref["logit_softcap_disabled"]

    cache_c = cache_b = None
    cur = prompt_ids[0]
    gen_ids, margins = [], []
    max_pos = max(targets)
    report = {"model": a.model, "layers": a.layers, "window": real_window, "prompt": a.prompt,
              "prompt_ids": prompt_ids, "targets": targets, "points": []}

    for pos in range(max_pos + 1):
        n_past = pos
        capture = capture_layers if n_past in targets else []
        logits_c, cache_c, acts_c = run_step(model, cache_c, cur, real_window, capture)
        logits_b, cache_b, acts_b = run_step(model, cache_b, cur, 10 ** 9, capture)

        if n_past in targets:
            top_c, top_b = torch.topk(logits_c.float(), 2), torch.topk(logits_b.float(), 2)
            point = {
                "n_past": n_past,
                "logits_rel_l2": rel_l2(logits_c, logits_b),
                "argmax_correct": int(top_c.indices[0]), "argmax_buggy": int(top_b.indices[0]),
                "argmax_changed": int(top_c.indices[0]) != int(top_b.indices[0]),
                "margin_correct": float(top_c.values[0] - top_c.values[1]),
                "attn_rel_l2": {str(i): rel_l2(acts_c[i], acts_b[i]) for i in capture_layers},
            }
            report["points"].append(point)
            print(f"[probe] n_past={n_past}: logits rel-L2={point['logits_rel_l2']:.6e} "
                  f"argmax {'CHANGED' if point['argmax_changed'] else 'same'} "
                  f"({point['argmax_correct']} vs {point['argmax_buggy']}) "
                  f"attn rel-L2={point['attn_rel_l2']}")

        top2 = torch.topk(logits_c.float(), 2)
        if pos + 1 < len(prompt_ids):
            cur = prompt_ids[pos + 1]
        else:
            gen_ids.append(int(top2.indices[0]))
            margins.append(float(top2.values[0] - top2.values[1]))
            cur = int(top2.indices[0])
        if len(gen_ids) == a.validate_steps and ref:
            ok = gen_ids == ref["gen_ids"][:a.validate_steps]
            print(f"[probe] validate vs {a.validate_ref}: {'PASS' if ok else 'MISMATCH'}\n"
                  f"[probe]   got      {gen_ids}\n[probe]   expected {ref['gen_ids'][:a.validate_steps]}")
            report["validate"] = {"pass": ok, "got": gen_ids,
                                  "expected": ref["gen_ids"][:a.validate_steps]}

    if a.out:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
        json.dump(report, open(a.out, "w"), indent=1)
        print(f"[probe] wrote {a.out}")
    return report


if __name__ == "__main__":
    main()
