#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# WHOLE-ARRAY (8-column) matmul with a FUSED epilogue. ONE xclbin computes
#     out = silu(A @ B + bias)          (silu mode,  bf16 out)
#     out =      A @ B + bias           (bias mode,  bf16 out, no activation)
# across all n_aie_cols columns (4 rows x 8 cols = 32 compute cores on NPU2),
# bf16 inputs, f32 in-core accumulate, bf16 output written to DDR.
#
# This merges two already-proven pieces in this repo:
#   1. whole_array_iron.py  -- the 8-column matmul that builds N=3072 in one shot
#      (n*n_aie_cols=256, 3072/256=12 row-blocks, well under the 64-BD limit, so
#       NO N-splitting is needed unlike the single-core design).
#   2. mm_silu_fused_iron.py (single core) -- the f32 acc_buf + mm_silu_epilogue +
#      f32->bf16 output ObjectFifo pattern, with BIAS folded by K-augmentation.
#
# WHAT CHANGED vs whole_array_iron.py:
#   * The C ObjectFifo chain (C_l1l2 / C_l2l3) carries the OUTPUT dtype (bf16),
#     not the f32 accumulator. The shim de-shuffle dims (c_dims) are pure
#     stride tuples and are dtype-independent, so they are unchanged.
#   * Each of the n_aie_rows*n_aie_cols workers gets its OWN core-local f32
#     accumulator Buffer (cacc_ty). The matmul reduces into that f32 buffer over
#     K; after the K reduction the epilogue kernel reads the f32 buffer, applies
#     silu (or a plain narrow in bias mode) and writes the bf16 C tile out.
#   * core_fn acquires the bf16 out tile, zeroes the f32 acc, runs the matmul
#     loop into the acc, then epilogue(acc, out_tile), then releases.
#
# BIAS via K-AUGMENTATION (host side, no third DMA input). The NPU2 compute tile
# has only 2 input DMA channels (A and B), so a separate bias stream does not
# fit. The host appends ONE extra k-block:
#     A_aug = [A | ones_col]   (extra k-block: col 0 = 1, rest 0)
#     B_aug = [B ; bias_row]   (extra k-block: row 0 = bias, rest 0)
#   A_aug @ B_aug = A@B + ones@bias = A@B + bias   (bias added to every row)
# So the device just runs a plain matmul with K = K_aug = K + k, then the
# epilogue. The runner script (run_npu_mm_silu_wa.py) builds A_aug/B_aug.
import argparse
import numpy as np

from aie.iron import (
    Buffer,
    Kernel,
    ObjectFifo,
    Program,
    Runtime,
    TaskGroup,
    Worker,
    WorkerRuntimeBarrier,
    str_to_dtype,
)
from aie.iron.device import NPU1Col1, NPU1Col2, NPU1, NPU2
from aie.iron.controlflow import range_
from aie.helpers.taplib import (
    TensorAccessPattern,
    TensorAccessSequence,
    TensorTiler2D,
)

def _str2bool(v):
    # Robustly parse 0/1/true/false. argparse type=bool is broken: bool("0")
    # is True (any non-empty string), so the native (emulate=0) build would
    # otherwise wrongly select the bfp16 microkernel dims. makefile-common
    # always passes --emulate-bf16-mmul-with-bfp16 {0|1}, so this generator
    # must accept "0".
    #
    # This is the SAME fix whole_array_iron.py already carries; it was never
    # propagated here, and the cost was a build that silently emitted a wrong
    # kernel. With type=bool the flag was a NO-OP: emulate=0 and emulate=1
    # generated BYTE-IDENTICAL MLIR (verified, 1542 lines, same sha256), so the
    # array program always used the r=8 emulated layout -- while
    # route_b_override.mk gates the KERNEL define on a make-level
    # `ifeq (...,1)`, which parses 0 correctly and dropped
    # -DAIE_API_EMULATE_BFLOAT16_MMUL_WITH_BFP16. An r=8 data layout feeding an
    # r=4 native microkernel is why the emulate=0 build measured rel-L2 1.367
    # against an fp32 reference -- worse than emitting zeros.
    return str(v).strip().lower() in ("1", "true", "yes", "on")


microkernel_mac_dim_map = {
    "npu": {
        "bf16": (4, 8, 4),
        "i8": (4, 8, 8),
        "i16": (4, 4, 4),
    },
    "npu2": {
        "bf16": {
            True: (8, 8, 8),
            False: (4, 8, 8),
        },
        "i8": (8, 8, 8),
        "i16": (4, 4, 8),
    },
}


def _stack_size():
    """Per-core stack reservation, overridable via WA_STACK_SIZE.

    0xD00 is a POLICY, not a derivation -- it is copy-pasted across 14 sites in this tree with no
    recorded frame measurement behind it. That matters because the generated linker script places the
    stack directly below the objectFIFO buffers with ZERO clearance (measured: 4874 of 4881 core
    scripts), so this number is the only thing between a kernel frame and silent buffer corruption --
    no crash, deterministic, surviving tiles bit-exact. Overridable so a suspected overflow can be
    tested in one build instead of being argued about.
    """
    import os as _os
    return int(_os.environ.get("WA_STACK_SIZE", "0xD00"), 0)


def ceildiv(a, b):
    return (a + b - 1) // b


def panel_major_c_taps(C_tiles, M, N, m, n, n_aie_rows, n_aie_cols, panel_w):
    """Re-stride the C drain TAPs so the shim writes C panel-major, not row-major.

    Row-major C is [M, N]; panel-major is [N//panel_w, M, panel_w], i.e.
        out[c, i, j] = C[i, c*panel_w + j].
    A consumer that contracts over a panel_w-wide K-slice of C can then take panel c
    as a plain contiguous device sub-buffer, which is the whole point: it deletes the
    separate packing command that used to materialise that layout.

    This is a pure re-stride of the SAME rank, the SAME sizes and the SAME walk order,
    so it changes only the shim BD in the runtime sequence -- the array program (cores,
    objectFIFOs, L1/L2 buffers) is untouched and the xclbin is unchanged.

    Each row-major drain TAP is the 4-D pattern [rb, g, r, j]
        C[ rb*(m*n_aie_rows) + r , g*(n_aie_cols*n) + col*n + j ]
    with offset col*n and strides [(m*n_aie_rows)*N, n_aie_cols*n, N, 1]. It only
    factors into panel-major without gaining a dimension when the panel boundary lands
    on the g stride, i.e. panel_w == n_aie_cols*n -- otherwise g would have to split
    into (panel, within-panel group) and the pattern would need 5 dims against the
    shim's 4. That is a hard requirement, not a preference, so assert it.
    """
    mb = m * n_aie_rows  # rows drained per tile-block
    group_w = n_aie_cols * n  # N covered by one pass across the columns
    if panel_w != group_w:
        raise AssertionError(
            f"c_panel_width={panel_w} must equal n_aie_cols*n={group_w}: the panel "
            "boundary has to coincide with the drain TAP's group stride, else the "
            "panel-major pattern needs 5 dims and will not fit a shim BD"
        )
    assert N % panel_w == 0, "N must be a whole number of panels"
    assert M % mb == 0, "M must be a whole number of tile-blocks"
    n_panels = N // panel_w

    # The STRIDES are the invariant that makes the re-stride valid; the outermost SIZE is
    # not (it is the tile-block group the runtime loop drains at a time, which equals
    # M//mb only when the two happen to coincide -- at m=64 they do, at m=32 they do not).
    # So assert the strides and the inner sizes, and read the rest off the TAP.
    want_strides = [mb * N, group_w, N, 1]
    # Same walk, new destination: g becomes the panel index, rb/r index rows within the
    # panel's [M, panel_w] plane, j stays the contiguous run.
    new_strides = [mb * panel_w, M * panel_w, panel_w, 1]

    out = []
    for t in C_tiles:
        sizes = list(t.sizes)
        if len(sizes) != 4 or list(t.strides) != want_strides:
            raise AssertionError(
                "C drain TAP is not the expected row-major [rb, g, r, j] pattern "
                f"(sizes {sizes} strides {list(t.strides)}, expected strides "
                f"{want_strides}); the panel-major re-stride assumes that structure"
            )
        if sizes[1:] != [N // group_w, mb, n]:
            raise AssertionError(
                f"C drain TAP inner sizes {sizes[1:]} != [{N // group_w}, {mb}, {n}]"
            )
        # The row-major offset carries two things: which tile-block row this drain starts
        # at, and this column's column start. Re-base only the row part -- under
        # panel_w == group_w the column part is already a within-panel column.
        row_base, col_start = divmod(t.offset, mb * N)
        assert col_start < group_w, "column offset must lie inside one panel"
        out.append(
            TensorAccessPattern(
                (n_panels * M, panel_w),
                row_base * mb * panel_w + col_start,
                sizes,
                new_strides,
            )
        )
    return out


def panel_major_a_taps(A_tiles, M, K, N, m_rows, k, n_aie_cols, n, panel_w):
    """Re-stride the A fill TAPs so the shim READS A panel-major, not row-major.

    The mirror of panel_major_c_taps, for the other end of the same seam: fc1 already
    DRAINS panel-major as [K//panel_w, M, panel_w], so a wide-K consumer can read that
    buffer directly instead of having it repacked. Same rank, same sizes product, same
    walk order, new strides -- instruction-stream only, array program untouched.

        A[i, j] == a_panel[j//panel_w, i, j%panel_w]

    The row-major fill TAP is the 4-D pattern [rep, kt, r, j] with strides
    [0, k, K, 1]: an outer REPEAT (stride 0, it re-reads the same A once per N-group),
    the k-tile index, the rows of one tile, and the contiguous run inside a k-tile.
    Panel-major needs the k-tile index split into (panel, k-tile-within-panel), which
    costs one dimension against the shim's limit of four. The only way it fits is by
    spending the repeat dimension -- so this is valid EXACTLY when that dimension is
    degenerate, i.e. when N//n//n_aie_cols == 1. That is a hard requirement, not a
    preference (it is why the fc2 seam works at N=1024 and would not at N=2048), so
    assert it rather than let it hold by luck. Same spirit as the panel_w == n_aie_cols*n
    assert on the C side.
    """
    repeat = N // n // n_aie_cols
    if repeat != 1:
        raise AssertionError(
            f"a_panel_width needs the A TAP's outer repeat dimension to be degenerate, "
            f"but N//n//n_aie_cols = {repeat}: with a real repeat the panel-major pattern "
            "needs 5 dims and will not fit a shim BD"
        )
    if K % panel_w:
        raise AssertionError(f"K={K} must be a whole number of {panel_w}-wide panels")
    if panel_w % k:
        raise AssertionError(
            f"panel_w={panel_w} must be a whole number of k={k} tiles, else a k-tile "
            "straddles a panel boundary and the split gains a dimension"
        )
    n_panels = K // panel_w
    want_strides = [0, k, K, 1]
    want_sizes = [repeat, K // k, m_rows, k]
    # panel replaces the repeat; kt now counts only within a panel; rows step by panel_w.
    new_sizes = [n_panels, panel_w // k, m_rows, k]
    new_strides = [M * panel_w, k, panel_w, 1]

    out = []
    for t in A_tiles:
        if list(t.sizes) != want_sizes or list(t.strides) != want_strides:
            raise AssertionError(
                "A fill TAP is not the expected row-major [rep, kt, r, j] pattern "
                f"(sizes {list(t.sizes)} strides {list(t.strides)}, expected "
                f"{want_sizes} / {want_strides}); the panel-major re-stride assumes it"
            )
        # A tap covers a whole row-block across every k-tile, so it starts at column 0
        # and its offset is purely the row start. Re-base that into a panel's [M, panel_w].
        row_start, col_start = divmod(t.offset, K)
        if col_start:
            raise AssertionError(
                f"A TAP offset {t.offset} is not a row boundary (col {col_start}); "
                "the panel-major re-base assumes each tap starts at column 0"
            )
        out.append(
            TensorAccessPattern(
                (n_panels * M, panel_w), row_start * panel_w, new_sizes, new_strides
            )
        )
    return out


def my_matmul(
    dev,
    M,
    K,
    N,
    m,
    k,
    n,
    n_aie_cols,
    b_col_maj,
    do_silu,
    emulate_bf16_mmul_with_bfp16,
    trace_size,
    generate_taps=False,
    do_gelu=False,
    do_glu=False,
    c_panel_width=0,
    dtype_out_str="f32",
    k_loop_rtp=False,
    a_panel_width=0,
    trace_worker=0,
):
    n_aie_rows = 4
    n_aie_cores = n_aie_rows * n_aie_cols

    # MODAL design: bf16 in / f32 accumulate. The OUTPUT dtype is f32 by default -- a HOST
    # consumer would otherwise have to re-expand bf16->f32 for its own math, which measured as
    # a net loss. bf16 out is for the one case where the consumer is another GEMM (bf16 in):
    # the fc1->fc2 seam, where it also halves the intermediate's DDR traffic. Note this changes
    # the L1/L2 C buffer sizes, i.e. the array program -- unlike --c-panel-width it is NOT an
    # instruction-stream-only change and produces a genuinely different xclbin.
    dtype_in_str = "bf16"
    dtype_acc_str = "f32"
    assert dtype_out_str in ("f32", "bf16"), "modal C is f32 or bf16"

    dtype_in = str_to_dtype(dtype_in_str)
    dtype_acc = str_to_dtype(dtype_acc_str)
    dtype_out = str_to_dtype(dtype_out_str)

    # r, s, t are the dimensions required by the microkernel MAC instructions.
    mac_dims = microkernel_mac_dim_map[dev]["bf16"]
    if dev == "npu2":
        r, s, t = mac_dims[emulate_bf16_mmul_with_bfp16]
    else:
        r, s, t = mac_dims

    if dev == "npu" and n_aie_cols > 4:
        raise AssertionError("Invalid configuration: NPU (Phoenix/Hawk) has 4 columns")
    if dev == "npu2" and n_aie_cols > 8:
        raise AssertionError(
            "Invalid configuration: NPU2 (Strix/Strix Halo/Krackan) has 8 columns"
        )

    assert (
        M % (m * n_aie_rows) == 0
    ), """A must be tileable into (m * n_aie_rows, k)-sized blocks"""
    assert K % k == 0
    assert (
        N % (n * n_aie_cols) == 0
    ), """B must be tileable into (k, n * n_aie_cols)-sized blocks"""
    assert m % r == 0
    assert k % s == 0
    assert n % t == 0
    assert (m * n) % 16 == 0, "epilogue walks the tile in 16-wide chunks"

    fifo_depth = 2
    # Single-buffer the C path on wide-N fast tiles (WA_C_DEPTH=1): the f32 acc_buf + a double-buffered
    # C overflows L1 at 64x32x96. Matches whole_array_iron.py's WA_C_DEPTH knob.
    import os as _os

    c_fifo_depth = int(_os.environ.get("WA_C_DEPTH", str(fifo_depth)))

    n_tiles_per_core = (M // m) * (N // n) // n_aie_cores

    if n_aie_cols > n_aie_rows:
        n_shim_mem_A = n_aie_rows
    else:
        n_shim_mem_A = n_aie_cols

    n_A_tiles_per_shim = n_aie_rows // n_aie_cols if n_aie_cols < 4 else 1

    if dev == "npu":
        if n_aie_cols == 1:
            dev_ty = NPU1Col1()
        elif n_aie_cols == 2:
            dev_ty = NPU1Col2()
        elif n_aie_cols == 4:
            dev_ty = NPU1()
    else:
        dev_ty = NPU2()

    A_taps = []
    B_taps = []
    C_taps = []

    # Define tensor types. NOTE: C / C_l2 / C_l1 are now OUTPUT dtype (bf16).
    A_ty = np.ndarray[(M * K,), np.dtype[dtype_in]]
    B_ty = np.ndarray[(K * N,), np.dtype[dtype_in]]
    C_ty = np.ndarray[(M * N,), np.dtype[dtype_out]]
    A_l2_ty = np.ndarray[(m * k * n_A_tiles_per_shim,), np.dtype[dtype_in]]
    B_l2_ty = np.ndarray[(k * n,), np.dtype[dtype_in]]
    C_l2_ty = np.ndarray[(m * n * n_aie_rows,), np.dtype[dtype_out]]
    A_l1_ty = np.ndarray[(m, k), np.dtype[dtype_in]]
    B_l1_ty = np.ndarray[(k, n), np.dtype[dtype_in]]
    C_l1_ty = np.ndarray[(m, n), np.dtype[dtype_out]]
    # Core-local f32 accumulator tile (one per worker).
    cacc_ty = np.ndarray[(m, n), np.dtype[dtype_acc]]

    # AIE Core Function declarations. The zero+matmul kernels operate on the f32
    # accumulator (cacc_ty); the epilogue reads f32 acc, writes bf16 out tile.
    zero_kernel = Kernel(f"zero_{dtype_acc_str}", f"mm_{m}x{k}x{n}.o", [cacc_ty])
    matmul_kernel = Kernel(
        f"matmul_{dtype_in_str}_{dtype_acc_str}",
        f"mm_{m}x{k}x{n}.o",
        [A_l1_ty, B_l1_ty, cacc_ty],
    )
    # MODAL f32-out epilogue: rtp[0] selects silu (1) vs identity (0) at runtime, so ONE xclbin
    # serves both via the inst-stream-baked rtp value (the do_silu build flag sets that value below).
    rtp_ty = np.ndarray[(16,), np.dtype[np.int32]]
    epilogue_kernel = Kernel(
        f"mm_modal_epilogue_f32_{dtype_out_str}",
        f"mm_silu_epilogue_{m}x{k}x{n}.o",
        [cacc_ty, C_l1_ty, rtp_ty],
    )

    # Tile declarations as tile[row][col]
    tiles = [[(col, row) for col in range(0, n_aie_cols)] for row in range(0, 6)]
    core_tiles = tiles[2:]

    # AIE-array data movement with object fifos
    A_l3l2_fifos = [None] * n_shim_mem_A
    A_l2l1_fifos = [None] * n_aie_rows

    B_l3l2_fifos = [None] * n_aie_cols
    B_l2l1_fifos = [None] * n_aie_cols

    C_l1l2_fifos = [[None] * n_aie_cols for _ in range(n_aie_rows)]
    C_l2l3_fifos = [None] * n_aie_cols

    # Input A
    for i in range(n_shim_mem_A):
        A_l3l2_fifos[i] = ObjectFifo(A_l2_ty, name=f"A_L3L2_{i}", depth=fifo_depth)
        start_row = i * n_A_tiles_per_shim
        stop_row = start_row + n_A_tiles_per_shim
        of_offsets = [m * k * j for j in range(stop_row - start_row)]
        dims_to_stream = [
            [
                (m // r, r * k),
                (k // s, s),
                (r, k),
                (s, 1),
            ]
        ] * (stop_row - start_row)
        a_tmp_fifos = (
            A_l3l2_fifos[i]
            .cons()
            .split(
                of_offsets,
                obj_types=[A_l1_ty] * (stop_row - start_row),
                names=[f"A_L2L1_{row}" for row in range(start_row, stop_row)],
                dims_to_stream=dims_to_stream,
            )
        )

        for j in range(stop_row - start_row):
            A_l2l1_fifos[j + start_row] = a_tmp_fifos[j]

    # Input B
    for col in range(n_aie_cols):
        B_l3l2_fifos[col] = ObjectFifo(B_l2_ty, name=f"B_L3L2_{col}", depth=fifo_depth)
        if b_col_maj:
            dims_to_stream = [(n // t, t * k), (k // s, s), (t, k), (s, 1)]
        else:
            dims_to_stream = [(k // s, s * n), (n // t, t), (s, n), (t, 1)]
        B_l2l1_fifos[col] = (
            B_l3l2_fifos[col]
            .cons()
            .forward(
                obj_type=B_l1_ty,
                name=f"B_L2L1_{col}",
                dims_to_stream=dims_to_stream,
            )
        )

        # Output C (bf16). The shim de-shuffle dims are dtype-independent stride
        # tuples (same as the plain matmul) -- they reorder the mmul-blocked tile
        # to row-major on the way to DDR.
        C_l2l3_fifos[col] = ObjectFifo(
            C_l2_ty,
            name=f"C_L2L3_{col}",
            depth=c_fifo_depth,
            dims_to_stream=[(m // r, r * n), (r, t), (n // t, r * t), (t, 1)],
        )
        of_offsets = [m * n * i for i in range(n_aie_rows)]

        c_tmp_fifos = (
            C_l2l3_fifos[col]
            .prod()
            .join(
                of_offsets,
                obj_types=[C_l1_ty] * n_aie_rows,
                names=[f"C_L1L2_{col}_{row}" for row in range(n_aie_rows)],
                depths=[c_fifo_depth] * n_aie_rows,
            )
        )
        for j in range(n_aie_rows):
            C_l1l2_fifos[j][col] = c_tmp_fifos[j]

    # Tasks for each worker to perform. Because the modal output is f32 (same dtype as the f32
    # accumulator), the matmul reduces DIRECTLY into the C output tile and the epilogue runs IN-PLACE
    # on it (silu/identity, f32->f32) — no separate acc_buf. That saves an m*n*4 L1 buffer per core,
    # which is what lets the wide-N fast tile (64x32x96) fit in L1.
    def core_fn(in_a, in_b, out_c, rtp_buff, barrier, zero, matmul, epilogue):
        barrier.wait_for_value(1)  # wait for the host to write the epilogue mode into rtp
        # k-loop-bound-as-rtp PoC: rtp[1] carries the K-tile trip count, written by sequence()
        # alongside rtp[0]'s epilogue mode, so ONE compiled core body serves any K value --
        # the loop bound is a runtime memref.load, not a Python-baked constant. range_/_for
        # accepts an MLIR Value as the loop stop, and AIESCFToControlFlow lowers it generically,
        # so no toolchain change is needed for this to work.
        loop = range(1)  # Workaround for issue #1547
        if n_tiles_per_core > 1:
            loop = range_(n_tiles_per_core)
        for _ in loop:
            # Load INSIDE the tile loop, matching where rtp[0] is read (the epilogue call below).
            # The core body is an infinite loop whose tile count is baked from the BUILD's N, while
            # a dispatch delivers the STREAM's N worth of tiles -- the two need not align, so one
            # body iteration can span several dispatches whenever stream N < build N. rtp is a
            # side-channel, not fifo-ordered, so anything hoisted above this loop is sampled once
            # per body iteration and pairs with whichever dispatch happened to enter it. That is
            # invisible while every stream shares K=1024, and silently wrong the moment two streams
            # carry different K -- which is the whole point of driving K from rtp.
            k_trip = rtp_buff[1] if k_loop_rtp else K // k
            elem_out = out_c.acquire(1)
            zero(elem_out)

            for _ in range_(k_trip):
                elem_in_a = in_a.acquire(1)
                elem_in_b = in_b.acquire(1)
                matmul(elem_in_a, elem_in_b, elem_out)
                in_a.release(1)
                in_b.release(1)
            epilogue(elem_out, elem_out, rtp_buff)  # in-place; rtp[0]: 1=silu, 0=identity
            out_c.release(1)

    # bf16-out sibling: the matmul reduces f32, so it CANNOT reduce into a bf16 C tile. This
    # variant keeps a core-local f32 accumulator and the epilogue narrows acc -> C on the way
    # out. That costs an extra m*n*4 L1 buffer per core, which is exactly the buffer the f32-out
    # modal deleted to make the wide-N fast tile fit -- so a bf16-out build has a tighter L1
    # budget and may need a smaller m. The allocator, not this comment, is the authority.
    def core_fn_split_acc(
        in_a, in_b, out_c, acc, rtp_buff, barrier, zero, matmul, epilogue
    ):
        barrier.wait_for_value(1)
        loop = range(1)  # Workaround for issue #1547
        if n_tiles_per_core > 1:
            loop = range_(n_tiles_per_core)
        for _ in loop:
            # Inside the tile loop, for the same reason as core_fn above: a body iteration can
            # span several dispatches, so a hoisted rtp read pairs with the wrong one.
            k_trip = rtp_buff[1] if k_loop_rtp else K // k
            elem_out = out_c.acquire(1)
            zero(acc)

            for _ in range_(k_trip):
                elem_in_a = in_a.acquire(1)
                elem_in_b = in_b.acquire(1)
                matmul(elem_in_a, elem_in_b, acc)
                in_a.release(1)
                in_b.release(1)
            epilogue(acc, elem_out, rtp_buff)  # f32 acc -> bf16 C; rtp[0] selects the mode
            out_c.release(1)

    # Per-core RTP (epilogue mode) + a shared runtime barrier. Each worker reads rtp[0].
    rtp_barrier = WorkerRuntimeBarrier()
    rtp_bufs = [
        [
            Buffer(rtp_ty, name=f"rtp_{row}_{col}", use_write_rtp=True)
            for col in range(n_aie_cols)
        ]
        for row in range(n_aie_rows)
    ]

    # Set up compute tiles. f32 out: in-place modal epilogue -> no per-core acc_buf (the matmul
    # reduces straight into C). bf16 out: a per-core f32 accumulator, narrowed by the epilogue.
    split_acc = dtype_out_str != dtype_acc_str
    workers = []
    for row in range(n_aie_rows):
        for col in range(n_aie_cols):
            args = [
                A_l2l1_fifos[row].cons(),
                B_l2l1_fifos[col].cons(),
                C_l1l2_fifos[row][col].prod(),
            ]
            if split_acc:
                args.append(Buffer(cacc_ty, name=f"cacc_{row}_{col}"))
            args += [
                rtp_bufs[row][col],
                rtp_barrier,
                zero_kernel,
                matmul_kernel,
                epilogue_kernel,
            ]
            workers.append(
                Worker(
                    core_fn_split_acc if split_acc else core_fn,
                    args,
                    stack_size=_stack_size(),
                )
            )

    tb_max_n_rows = 4
    # DERIVED, not `tb_max_n_rows // 2`: the C tiler below asks for exactly this many row-blocks, so a
    # bare 2 forces M % (2 * m * n_aie_rows) == 0 -- i.e. M % 512 == 0 for the shipped 64x32x128 tile.
    # That constraint is what makes PAD_M 512 and leaves 66-90% of every modal GEMM's rows as padding
    # at the encoder's T=52..172. The RUNTIME loop already clamps the same quantity
    # (`min(tb_max_n_rows // 2, M // m // n_aie_rows - row_base)`), so the tiler was the only place
    # assuming two blocks exist.
    tb_n_rows = min(tb_max_n_rows // 2, M // m // n_aie_rows)

    A_tiles = TensorTiler2D.group_tiler(
        (M, K),
        (m * n_A_tiles_per_shim, k),
        (1, K // k),
        pattern_repeat=N // n // n_aie_cols,
        prune_step=False,
    )
    if a_panel_width:
        # Read A straight out of the producer's [K//W, M, W] panel-major buffer (fc1's
        # default bf16 drain), so a wide-K GEMM needs no repack. Insts-only, same as the
        # C-side panel drain.
        A_tiles = panel_major_a_taps(
            A_tiles, M, K, N, m * n_A_tiles_per_shim, k, n_aie_cols, n, a_panel_width
        )
    if b_col_maj:
        B_tiles = TensorTiler2D.step_tiler(
            (N, K),
            (n, k),
            tile_group_repeats=(N // n // n_aie_cols, K // k),
            tile_group_steps=(n_aie_cols, 1),
            prune_step=False,
        )
    else:
        B_tiles = TensorTiler2D.step_tiler(
            (K, N),
            (k, n),
            tile_group_repeats=(K // k, N // n // n_aie_cols),
            tile_group_steps=(1, n_aie_cols),
            tile_group_col_major=True,
            prune_step=False,
        )
    C_tiles = TensorTiler2D.step_tiler(
        (M, N),
        (m * n_aie_rows, n),
        tile_group_repeats=(tb_n_rows, N // n // n_aie_cols),
        tile_group_steps=(1, n_aie_cols),
        prune_step=False,
    )
    if c_panel_width:
        # Drain C straight into the [N//c_panel_width, M, c_panel_width] panel-major layout
        # the consumer wants. Insts-only: same rank/sizes/order, new strides.
        C_tiles = panel_major_c_taps(
            C_tiles, M, N, m, n, n_aie_rows, n_aie_cols, c_panel_width
        )
    c_index = 0

    def sequence(A, B, C, A_prods, B_prods, C_conses):
        nonlocal c_index
        # bake the epilogue mode into this instruction stream's RTP (1=silu, 0=identity), then
        # release the barrier so the cores read it. A silu-built stream and an identity-built stream
        # are two .txt insts on the SAME xclbin -> the host picks mode by choosing the stream.
        # rtp[0]: 0=identity, 1=silu, 2=gelu, 3=glu. GLU halves the LIVE output width (it writes
        # into the value half of each tile and leaves the accumulator in the gate half), but the
        # drain stays FULL width -- a narrower tap would change the TAP SIZES, and the insts-only
        # property holds only for a re-stride at constant sizes. The consumer reads the strided
        # subset instead. So no tap change here, deliberately.
        mode_val = 3 if do_glu else (2 if do_gelu else (1 if do_silu else 0))
        for r in range(n_aie_rows):
            for c in range(n_aie_cols):
                rtp_bufs[r][c][0] = mode_val
                if k_loop_rtp:
                    rtp_bufs[r][c][1] = K // k  # k-loop-bound-as-rtp PoC: K-tile trip count
        rtp_barrier.set(1)

        tg = TaskGroup()
        for tb in range(ceildiv(M // m // n_aie_rows, tb_max_n_rows)):
            for pingpong in [0, 1]:
                if c_index >= len(C_tiles):
                    break

                row_base = tb * tb_max_n_rows + pingpong * tb_max_n_rows // 2
                current_tb_n_rows = min(
                    [tb_max_n_rows // 2, M // m // n_aie_rows - row_base]
                )

                for col in range(n_aie_cols):
                    C_taps.append(C_tiles[c_index])
                    C_conses[col].drain(
                        C,
                        tap=C_tiles[c_index],
                        wait=True,
                        group=tg,
                    )
                    c_index += 1

                    for tile_row in range(current_tb_n_rows):
                        tile_offset = (
                            (row_base + tile_row) * n_shim_mem_A + col
                        ) % len(A_tiles)

                        if col < n_aie_rows:
                            A_prods[col].fill(
                                A,
                                tap=A_tiles[tile_offset],
                                group=tg,
                            )

                        B_prods[col].fill(
                            B,
                            tap=B_tiles[col],
                            group=tg,
                        )

                        A_taps.append(A_tiles[tile_offset])
                        B_taps.append(B_tiles[col])
                if tb > 0 or (tb == 0 and pingpong > 0):
                    tg.finish()
                    tg = TaskGroup()
        tg.finish()

    rt = Runtime(
        sequence,
        [
            A_ty,
            B_ty,
            C_ty,
            [f.prod() for f in A_l3l2_fifos],
            [f.prod() for f in B_l3l2_fifos],
            [f.cons() for f in C_l2l3_fifos],
        ],
    )

    my_program = Program(dev_ty, rt, workers=workers)
    # Per-op occupancy instrument. `trace_size=0` (production) leaves the design byte-identical.
    # Trace ONE worker: every worker runs the identical tile loop, so one is representative.
    #
    # WHICH worker is not free. A core tile has 4 South egress ports and, in column 0, no West;
    # this design sends every core's C stream downward, so the bottom tile carries its own C plus
    # the rows above it. Measured 2026-08-17 on the pinned toolchain (N=1024, m/k/n 64/32/128,
    # WA_C_DEPTH=1), cols=1 South-out usage is (0,2) 4/4, (0,3) 3/4, (0,4) 2/4, (0,5) 1/4 -- so
    # tracing workers[0] at row 2 has nowhere to go and the packet never leaves the tile. That is
    # why no destination-side lever moves it: lateral-routing and egress_shim_col 0/1/4 all fail
    # identically. Tracing a HIGHER row routes.
    #
    # By width: cols=4 builds green (verified through aiecc, not just the pathfinder) with any
    # worker; cols=1 needs worker >= 1; cols=8 does not route at any worker or egress column,
    # because its production routing already pins (0,2) and (0,4) at 4/4. Getting cols=8 traced
    # needs fewer downward C streams per column, not a flag.
    if trace_size:
        my_program.enable_trace(
            trace_size=trace_size,
            workers=[workers[trace_worker]],
            egress_shim_col=0,
        )
    # seq_fn now runs at resolve time, so the tap lists are only populated after
    # this call -- generate_taps must return AFTER it, not before.
    module = my_program.resolve_program()

    if generate_taps:
        return (
            TensorAccessSequence.from_taps(A_taps),
            TensorAccessSequence.from_taps(B_taps),
            TensorAccessSequence.from_taps(C_taps),
        )

    return module


def main():
    argparser = argparse.ArgumentParser(
        prog="AIE whole-array fused matmul + bias (+ optional SiLU)",
        description="silu(A@B+bias) or A@B+bias across all columns, bf16 in/out, "
        "f32 accumulate, single xclbin",
    )
    argparser.add_argument("--dev", type=str, choices=["npu", "npu2"], default="npu2")
    argparser.add_argument("-M", type=int, default=512)
    argparser.add_argument("-K", type=int, default=768)
    argparser.add_argument("-N", type=int, default=3072)
    argparser.add_argument("-m", type=int, default=32)
    argparser.add_argument("-k", type=int, default=32)
    argparser.add_argument("-n", type=int, default=32)
    argparser.add_argument("--n-aie-cols", type=int, choices=[1, 2, 4, 8], default=8)
    argparser.add_argument("--b-col-maj", type=int, choices=[0, 1], default=0)
    argparser.add_argument(
        "--no-silu",
        action="store_true",
        help="bias mode: out = A@B+bias (plain f32->bf16 narrow, no activation). "
        "Default is silu mode: out = silu(A@B+bias).",
    )
    argparser.add_argument(
        "--gelu",
        action="store_true",
        help="gelu mode: out = gelu(A@B+bias) (tanh approx). Folds the Whisper encoder FFN activation "
        "into the fc1 epilogue. Overrides --no-silu. rtp[0]=2.",
    )
    argparser.add_argument(
        "--emulate-bf16-mmul-with-bfp16", type=_str2bool, default=False
    )
    # Accepted for makefile-common compatibility; this design is fixed to
    # bf16 in / f32 accumulate / bf16 out.
    argparser.add_argument("--dtype_in", type=str, default="bf16", choices=["bf16"])
    argparser.add_argument(
        "--dtype_out", type=str, default="f32", choices=["f32", "bf16"]
    )
    argparser.add_argument("--trace_size", type=int, default=0)
    # Index into `workers`, not a tile coordinate. Row 2 (index 0) is the C-stream aggregation
    # point and has no free South port -- see the enable_trace comment for the per-width table.
    argparser.add_argument("--trace_worker", type=int, default=0)
    argparser.add_argument("--generate-taps", action="store_true")
    argparser.add_argument(
        "--c-panel-width",
        type=int,
        default=0,
        help="drain C panel-major as [N/W, M, W] instead of row-major [M, N] (0 = off). "
        "Must equal n_aie_cols*n. Lets a K-split consumer take each panel as a contiguous "
        "device sub-buffer, deleting the separate deinterleave dispatch. Insts-only: the "
        "xclbin is byte-identical to the row-major build.",
    )
    argparser.add_argument(
        "--glu",
        action="store_true",
        help="glu mode: out = a * sigmoid(g) over the tile's [value|gate] halves (rtp[0]=3). Folds the "
        "conv-module GLU into pw1's epilogue. REQUIRES W1's columns permuted at weight load so each "
        "tile holds 64 value columns and their 64 gate partners; without that the pairing is wrong and "
        "silently so. Overrides --gelu/--no-silu. Drain stays full width by design.",
    )
    argparser.add_argument(
        "--a-panel-width",
        type=int,
        default=0,
        help="read A from a [K//W, M, W] panel-major buffer instead of row-major [M, K] "
        "(0 = off). The mirror of --c-panel-width, for consuming a producer that already "
        "drained panel-major. Insts-only. Requires N//n//n_aie_cols == 1, since the panel "
        "index spends the A TAP's outer repeat dimension.",
    )
    argparser.add_argument(
        "--k-loop-rtp",
        action="store_true",
        help="k-loop-bound-as-rtp PoC: drive the core's K-tile loop bound from rtp[1] "
        "(a runtime memref.load) instead of baking K//k as a compile-time constant. "
        "Claim under test: the xclbin/core-ELF becomes independent of K, so only the "
        "insts stream (A/B tap counts + the rtp[1] write) needs to vary per K value.",
    )
    args = argparser.parse_args()
    maybe_module = my_matmul(
        args.dev,
        args.M,
        args.K,
        args.N,
        args.m,
        args.k,
        args.n,
        args.n_aie_cols,
        args.b_col_maj,
        not args.no_silu,
        args.emulate_bf16_mmul_with_bfp16,
        args.trace_size,
        args.generate_taps,
        args.gelu,
        args.glu,
        args.c_panel_width,
        args.dtype_out,
        args.k_loop_rtp,
        args.a_panel_width,
        args.trace_worker,
    )
    if args.generate_taps:
        return maybe_module
    else:
        print(maybe_module)


if __name__ == "__main__":
    main()
