#
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025 Advanced Micro Devices, Inc. or its affiliates
#
# WHOLE-ARRAY (8-column) matmul with a FUSED epilogue. ONE xclbin computes
#     out = silu(A @ B + bias)          (silu mode,  bf16 out)
#     out =      A @ B + bias           (bias mode,  bf16 out, no activation)
# across all n_aie_cols columns (4 rows x 8 cols = 32 compute cores on NPU2),
# bf16 inputs, f32 in-core accumulate, bf16 output written to DDR.
#
# This merges two already-proven pieces in this repo:
#   1. whole_array_iron.py  -- the 8-column matmul that builds N=3072 in one shot
#      (n*n_aie_cols=256, 3072/256=12 row-blocks, well under the 64-BD limit, so
#       NO N-splitting is needed unlike the single-core design).
#   2. mm_silu_fused_iron.py (single core) -- the f32 acc_buf + mm_silu_epilogue +
#      f32->bf16 output ObjectFifo pattern, with BIAS folded by K-augmentation.
#
# WHAT CHANGED vs whole_array_iron.py:
#   * The C ObjectFifo chain (C_l1l2 / C_l2l3) carries the OUTPUT dtype (bf16),
#     not the f32 accumulator. The shim de-shuffle dims (c_dims) are pure
#     stride tuples and are dtype-independent, so they are unchanged.
#   * Each of the n_aie_rows*n_aie_cols workers gets its OWN core-local f32
#     accumulator Buffer (cacc_ty). The matmul reduces into that f32 buffer over
#     K; after the K reduction the epilogue kernel reads the f32 buffer, applies
#     silu (or a plain narrow in bias mode) and writes the bf16 C tile out.
#   * core_fn acquires the bf16 out tile, zeroes the f32 acc, runs the matmul
#     loop into the acc, then epilogue(acc, out_tile), then releases.
#
# BIAS via K-AUGMENTATION (host side, no third DMA input). The NPU2 compute tile
# has only 2 input DMA channels (A and B), so a separate bias stream does not
# fit. The host appends ONE extra k-block:
#     A_aug = [A | ones_col]   (extra k-block: col 0 = 1, rest 0)
#     B_aug = [B ; bias_row]   (extra k-block: row 0 = bias, rest 0)
#   A_aug @ B_aug = A@B + ones@bias = A@B + bias   (bias added to every row)
# So the device just runs a plain matmul with K = K_aug = K + k, then the
# epilogue. The runner script (run_npu_mm_silu_wa.py) builds A_aug/B_aug.
import argparse
import numpy as np

from aie.iron import (
    Buffer,
    Kernel,
    ObjectFifo,
    Program,
    Runtime,
    TaskGroup,
    Worker,
    WorkerRuntimeBarrier,
    str_to_dtype,
)
from aie.iron.device import NPU1Col1, NPU1Col2, NPU1, NPU2
from aie.iron.controlflow import range_
from aie.helpers.dialects.scf import if_ as scf_if_, else_ as scf_else_
from aie.dialects import arith as _arith
from aie.extras import types as _T
from aie.helpers.taplib import (
    TensorAccessPattern,
    TensorAccessSequence,
    TensorTiler2D,
)

def _str2bool(v):
    # Robustly parse 0/1/true/false. argparse type=bool is broken: bool("0")
    # is True (any non-empty string), so the native (emulate=0) build would
    # otherwise wrongly select the bfp16 microkernel dims. makefile-common
    # always passes --emulate-bf16-mmul-with-bfp16 {0|1}, so this generator
    # must accept "0".
    #
    # This is the SAME fix whole_array_iron.py already carries; it was never
    # propagated here, and the cost was a build that silently emitted a wrong
    # kernel. With type=bool the flag was a NO-OP: emulate=0 and emulate=1
    # generated BYTE-IDENTICAL MLIR (verified, 1542 lines, same sha256), so the
    # array program always used the r=8 emulated layout -- while
    # route_b_override.mk gates the KERNEL define on a make-level
    # `ifeq (...,1)`, which parses 0 correctly and dropped
    # -DAIE_API_EMULATE_BFLOAT16_MMUL_WITH_BFP16. An r=8 data layout feeding an
    # r=4 native microkernel is why the emulate=0 build measured rel-L2 1.367
    # against an fp32 reference -- worse than emitting zeros.
    return str(v).strip().lower() in ("1", "true", "yes", "on")


microkernel_mac_dim_map = {
    "npu": {
        "bf16": (4, 8, 4),
        "i8": (4, 8, 8),
        "i16": (4, 4, 4),
    },
    "npu2": {
        "bf16": {
            True: (8, 8, 8),
            False: (4, 8, 8),
        },
        "i8": (8, 8, 8),
        "i16": (4, 4, 8),
    },
}


def _stack_size():
    """Per-core stack reservation, overridable via WA_STACK_SIZE.

    0xD00 is a POLICY, not a derivation -- it is copy-pasted across 14 sites in this tree with no
    recorded frame measurement behind it. That matters because the generated linker script places the
    stack directly below the objectFIFO buffers with ZERO clearance (measured: 4874 of 4881 core
    scripts), so this number is the only thing between a kernel frame and silent buffer corruption --
    no crash, deterministic, surviving tiles bit-exact. Overridable so a suspected overflow can be
    tested in one build instead of being argued about.
    """
    import os as _os
    return int(_os.environ.get("WA_STACK_SIZE", "0xD00"), 0)


def _trace_event(spec):
    """One --trace_events item: a bare CoreEvent name, or a PORT_* event bound to a port.

    A PORT_* name selects a monitor SLOT, not a port -- the slot counts nothing until it is
    pointed at one. The default core set binds slot 0 to DMA ch0 in and slot 1 to DMA ch0 OUT
    (aie.utils.trace.setup), so `PORT_RUNNING_1` alone does not mean channel 1 and the second
    input channel is unreachable by name. Bind it explicitly as NAME:BUNDLE:CHANNEL:DIR, e.g.
    PORT_RUNNING_1:DMA:1:in.

    This design puts A on S2MM ch0 and B on S2MM ch1 (one dma_start each, in the generated
    aie.mem), so a run without an explicit ch1 binding measures the A feed alone.

    Events sharing a slot must agree on the binding -- PORT_RUNNING_0 and PORT_STALLED_0 both
    watch slot 0, which is how running-vs-backpressured is read off one port.
    """
    from aie.dialects.aie import WireBundle
    from aie.utils.trace.events import CoreEvent, PortEvent

    parts = [p.strip() for p in spec.split(":")]
    code = getattr(CoreEvent, parts[0])
    if len(parts) == 1:
        return code
    if len(parts) != 4:
        raise ValueError(f"port event wants NAME:BUNDLE:CHANNEL:DIR, got {spec!r}")
    bundle, channel, direction = parts[1], int(parts[2]), parts[3].lower()
    if direction not in ("in", "out"):
        raise ValueError(f"direction is in|out, got {parts[3]!r} in {spec!r}")
    return PortEvent(
        code, port=getattr(WireBundle, bundle), channel=channel, master=(direction == "in")
    )


def _memtile_trace_event(spec):
    """One --trace_memtile_events item, in MemTileEvent space rather than CoreEvent space.

    Same NAME[:BUNDLE:CHANNEL:DIR] grammar as _trace_event, and the same trap: a PORT_* name is a
    monitor SLOT. The memtile default set binds slots 0-3 to DMA ch0-3 IN and 4-7 to ch0-3 OUT, so
    an unbound PORT_RUNNING_1 watches an INPUT channel here.

    DIR follows aie.utils.trace.setup's own convention -- master=True is "in" (S2MM), False is
    "out" (MM2S). This design pushes A on memtile MM2S ch0 and B on MM2S ch1, so the two feeds at
    their SOURCE are PORT_RUNNING_x:DMA:0:out and :DMA:1:out.

    The DMA_MM2S_SEL{0,1}_* counters are a SEPARATE mechanism: which channel each SEL watches comes
    from the memtile's DMA_EVENT_CHANNEL_SELECTION register, which mlir-aie never writes, so they
    sit at the reset default. Treat that as unverified and gate it -- pair each SEL event with the
    explicitly-bound PORT_RUNNING for the channel it is supposed to be, and check the windows agree.
    """
    from aie.dialects.aie import WireBundle
    from aie.utils.trace.events import MemTileEvent, MemTilePortEvent

    parts = [p.strip() for p in spec.split(":")]
    code = getattr(MemTileEvent, parts[0])
    if len(parts) == 1:
        return code
    if len(parts) != 4:
        raise ValueError(f"port event wants NAME:BUNDLE:CHANNEL:DIR, got {spec!r}")
    bundle, channel, direction = parts[1], int(parts[2]), parts[3].lower()
    if direction not in ("in", "out"):
        raise ValueError(f"direction is in|out, got {parts[3]!r} in {spec!r}")
    return MemTilePortEvent(
        code, port=getattr(WireBundle, bundle), channel=channel, master=(direction == "in")
    )


def ceildiv(a, b):
    return (a + b - 1) // b


def panel_major_c_taps(C_tiles, M, N, m, n, n_aie_rows, n_aie_cols, panel_w):
    """Re-stride the C drain TAPs so the shim writes C panel-major, not row-major.

    Row-major C is [M, N]; panel-major is [N//panel_w, M, panel_w], i.e.
        out[c, i, j] = C[i, c*panel_w + j].
    A consumer that contracts over a panel_w-wide K-slice of C can then take panel c
    as a plain contiguous device sub-buffer, which is the whole point: it deletes the
    separate packing command that used to materialise that layout.

    This is a pure re-stride of the SAME rank, the SAME sizes and the SAME walk order,
    so it changes only the shim BD in the runtime sequence -- the array program (cores,
    objectFIFOs, L1/L2 buffers) is untouched and the xclbin is unchanged.

    Each row-major drain TAP is the 4-D pattern [rb, g, r, j]
        C[ rb*(m*n_aie_rows) + r , g*(n_aie_cols*n) + col*n + j ]
    with offset col*n and strides [(m*n_aie_rows)*N, n_aie_cols*n, N, 1]. It only
    factors into panel-major without gaining a dimension when the panel boundary lands
    on the g stride, i.e. panel_w == n_aie_cols*n -- otherwise g would have to split
    into (panel, within-panel group) and the pattern would need 5 dims against the
    shim's 4. That is a hard requirement, not a preference, so assert it.
    """
    mb = m * n_aie_rows  # rows drained per tile-block
    group_w = n_aie_cols * n  # N covered by one pass across the columns
    if panel_w != group_w:
        raise AssertionError(
            f"c_panel_width={panel_w} must equal n_aie_cols*n={group_w}: the panel "
            "boundary has to coincide with the drain TAP's group stride, else the "
            "panel-major pattern needs 5 dims and will not fit a shim BD"
        )
    assert N % panel_w == 0, "N must be a whole number of panels"
    assert M % mb == 0, "M must be a whole number of tile-blocks"
    n_panels = N // panel_w

    # The STRIDES are the invariant that makes the re-stride valid; the outermost SIZE is
    # not (it is the tile-block group the runtime loop drains at a time, which equals
    # M//mb only when the two happen to coincide -- at m=64 they do, at m=32 they do not).
    # So assert the strides and the inner sizes, and read the rest off the TAP.
    want_strides = [mb * N, group_w, N, 1]
    # Same walk, new destination: g becomes the panel index, rb/r index rows within the
    # panel's [M, panel_w] plane, j stays the contiguous run.
    new_strides = [mb * panel_w, M * panel_w, panel_w, 1]

    out = []
    for t in C_tiles:
        sizes = list(t.sizes)
        if len(sizes) != 4 or list(t.strides) != want_strides:
            raise AssertionError(
                "C drain TAP is not the expected row-major [rb, g, r, j] pattern "
                f"(sizes {sizes} strides {list(t.strides)}, expected strides "
                f"{want_strides}); the panel-major re-stride assumes that structure"
            )
        if sizes[1:] != [N // group_w, mb, n]:
            raise AssertionError(
                f"C drain TAP inner sizes {sizes[1:]} != [{N // group_w}, {mb}, {n}]"
            )
        # The row-major offset carries two things: which tile-block row this drain starts
        # at, and this column's column start. Re-base only the row part -- under
        # panel_w == group_w the column part is already a within-panel column.
        row_base, col_start = divmod(t.offset, mb * N)
        assert col_start < group_w, "column offset must lie inside one panel"
        out.append(
            TensorAccessPattern(
                (n_panels * M, panel_w),
                row_base * mb * panel_w + col_start,
                sizes,
                new_strides,
            )
        )
    return out


def panel_major_a_taps(A_tiles, M, K, N, m_rows, k, n_aie_cols, n, panel_w):
    """Re-stride the A fill TAPs so the shim READS A panel-major, not row-major.

    The mirror of panel_major_c_taps, for the other end of the same seam: fc1 already
    DRAINS panel-major as [K//panel_w, M, panel_w], so a wide-K consumer can read that
    buffer directly instead of having it repacked. Same rank, same sizes product, same
    walk order, new strides -- instruction-stream only, array program untouched.

        A[i, j] == a_panel[j//panel_w, i, j%panel_w]

    The row-major fill TAP is the 4-D pattern [rep, kt, r, j] with strides
    [0, k, K, 1]: an outer REPEAT (stride 0, it re-reads the same A once per N-group),
    the k-tile index, the rows of one tile, and the contiguous run inside a k-tile.
    Panel-major needs the k-tile index split into (panel, k-tile-within-panel), which
    costs one dimension against the shim's limit of four. The only way it fits is by
    spending the repeat dimension -- so this is valid EXACTLY when that dimension is
    degenerate, i.e. when N//n//n_aie_cols == 1. That is a hard requirement, not a
    preference (it is why the fc2 seam works at N=1024 and would not at N=2048), so
    assert it rather than let it hold by luck. Same spirit as the panel_w == n_aie_cols*n
    assert on the C side.
    """
    repeat = N // n // n_aie_cols
    if repeat != 1:
        raise AssertionError(
            f"a_panel_width needs the A TAP's outer repeat dimension to be degenerate, "
            f"but N//n//n_aie_cols = {repeat}: with a real repeat the panel-major pattern "
            "needs 5 dims and will not fit a shim BD"
        )
    if K % panel_w:
        raise AssertionError(f"K={K} must be a whole number of {panel_w}-wide panels")
    if panel_w % k:
        raise AssertionError(
            f"panel_w={panel_w} must be a whole number of k={k} tiles, else a k-tile "
            "straddles a panel boundary and the split gains a dimension"
        )
    n_panels = K // panel_w
    want_strides = [0, k, K, 1]
    want_sizes = [repeat, K // k, m_rows, k]
    # panel replaces the repeat; kt now counts only within a panel; rows step by panel_w.
    new_sizes = [n_panels, panel_w // k, m_rows, k]
    new_strides = [M * panel_w, k, panel_w, 1]

    out = []
    for t in A_tiles:
        if list(t.sizes) != want_sizes or list(t.strides) != want_strides:
            raise AssertionError(
                "A fill TAP is not the expected row-major [rep, kt, r, j] pattern "
                f"(sizes {list(t.sizes)} strides {list(t.strides)}, expected "
                f"{want_sizes} / {want_strides}); the panel-major re-stride assumes it"
            )
        # A tap covers a whole row-block across every k-tile, so it starts at column 0
        # and its offset is purely the row start. Re-base that into a panel's [M, panel_w].
        row_start, col_start = divmod(t.offset, K)
        if col_start:
            raise AssertionError(
                f"A TAP offset {t.offset} is not a row boundary (col {col_start}); "
                "the panel-major re-base assumes each tap starts at column 0"
            )
        out.append(
            TensorAccessPattern(
                (n_panels * M, panel_w), row_start * panel_w, new_sizes, new_strides
            )
        )
    return out


def my_matmul(
    dev,
    M,
    K,
    N,
    m,
    k,
    n,
    n_aie_cols,
    b_col_maj,
    do_silu,
    emulate_bf16_mmul_with_bfp16,
    trace_size,
    generate_taps=False,
    do_gelu=False,
    do_glu=False,
    c_panel_width=0,
    dtype_out_str="f32",
    k_loop_rtp=False,
    a_panel_width=0,
    trace_worker=0,
    trace_events=None,
    trace_memtile=-1,
    trace_memtile_events=None,
    mode_resadd=False,
    rtp_mode_resadd=False,
    resadd_only=False,
    mode_read_late=False,
    k_read_late=False,
    mode_lnaffcast=0,
    rtp_mode_lnaffcast=False,
    lnaffcast_rows=0,
    lnaffcast_c_fanout=False,
    lnaffcast_group_rounds=1,
    lnaffcast_contig_taps="",
    lnaffcast_1x=False,
    mode_resadd2a=False,
    rtp_mode_resadd2a=False,
    resadd2a_rows=0,
    resadd2a_scale=1.0,
    resadd2a_rev_rows=False,
):
    n_aie_rows = 4
    n_aie_cores = n_aie_rows * n_aie_cols

    # MODAL design: bf16 in / f32 accumulate. The OUTPUT dtype is f32 by default -- a HOST
    # consumer would otherwise have to re-expand bf16->f32 for its own math, which measured as
    # a net loss. bf16 out is for the one case where the consumer is another GEMM (bf16 in):
    # the fc1->fc2 seam, where it also halves the intermediate's DDR traffic. Note this changes
    # the L1/L2 C buffer sizes, i.e. the array program -- unlike --c-panel-width it is NOT an
    # instruction-stream-only change and produces a genuinely different xclbin.
    dtype_in_str = "bf16"
    dtype_acc_str = "f32"
    assert dtype_out_str in ("f32", "bf16"), "modal C is f32 or bf16"

    dtype_in = str_to_dtype(dtype_in_str)
    dtype_acc = str_to_dtype(dtype_acc_str)
    dtype_out = str_to_dtype(dtype_out_str)

    # r, s, t are the dimensions required by the microkernel MAC instructions.
    mac_dims = microkernel_mac_dim_map[dev]["bf16"]
    if dev == "npu2":
        r, s, t = mac_dims[emulate_bf16_mmul_with_bfp16]
    else:
        r, s, t = mac_dims

    if dev == "npu" and n_aie_cols > 4:
        raise AssertionError("Invalid configuration: NPU (Phoenix/Hawk) has 4 columns")
    if dev == "npu2" and n_aie_cols > 8:
        raise AssertionError(
            "Invalid configuration: NPU2 (Strix/Strix Halo/Krackan) has 8 columns"
        )

    assert (
        M % (m * n_aie_rows) == 0
    ), """A must be tileable into (m * n_aie_rows, k)-sized blocks"""
    assert K % k == 0
    assert (
        N % (n * n_aie_cols) == 0
    ), """B must be tileable into (k, n * n_aie_cols)-sized blocks"""
    assert m % r == 0
    assert k % s == 0
    assert n % t == 0
    assert (m * n) % 16 == 0, "epilogue walks the tile in 16-wide chunks"

    fifo_depth = 2
    # Single-buffer the C path on wide-N fast tiles (WA_C_DEPTH=1): the f32 acc_buf + a double-buffered
    # C overflows L1 at 64x32x96. Matches whole_array_iron.py's WA_C_DEPTH knob.
    import os as _os

    c_fifo_depth = int(_os.environ.get("WA_C_DEPTH", str(fifo_depth)))
    # Same knob for the L1 side of A and B (WA_AB_DEPTH=1). At m=64/n=128 the depth-2 A+B pair is
    # 48 KB of a 64 KB L1 against C's 32 KB, so k cannot rise past 32 without spending it: k=64
    # fails allocation outright. Single-buffering trades DMA/compute overlap for K amortization,
    # and the k=32 trace says that overlap is currently idle -- objectfifo_wait 0%, DISABLED never
    # fires, INSTR_LOCK_ACQUIRE_REQ 0.06%. Only the L1 side; the L2 fifos are not the constraint.
    ab_fifo_depth = int(_os.environ.get("WA_AB_DEPTH", str(fifo_depth)))
    # The L3->L2 hop (WA_L3L2_DEPTH). WA_AB_DEPTH above sizes only L2->L1; the shim-to-memtile
    # fifos stayed at 2 in every arm of the K/depth sweeps, so "the L2 fifos are not the
    # constraint" was assumed, never measured. Deepening L2->L1 2->3->4 moved LOCK_STALL by 1.8%
    # with no trend, so if the acquire wait is a feed-rate problem it has to be upstream of that.
    # L2 is 512 KB/col against an A+B L2 pair of k*(m*n_aie_rows + n)*2 B, so depth 4 fits easily.
    l3l2_fifo_depth = int(_os.environ.get("WA_L3L2_DEPTH", str(fifo_depth)))

    n_tiles_per_core = (M // m) * (N // n) // n_aie_cores

    if n_aie_cols > n_aie_rows:
        n_shim_mem_A = n_aie_rows
    else:
        n_shim_mem_A = n_aie_cols

    n_A_tiles_per_shim = n_aie_rows // n_aie_cols if n_aie_cols < 4 else 1

    if dev == "npu":
        if n_aie_cols == 1:
            dev_ty = NPU1Col1()
        elif n_aie_cols == 2:
            dev_ty = NPU1Col2()
        elif n_aie_cols == 4:
            dev_ty = NPU1()
    else:
        dev_ty = NPU2()

    A_taps = []
    B_taps = []
    C_taps = []

    # Define tensor types. NOTE: C / C_l2 / C_l1 are now OUTPUT dtype (bf16).
    A_ty = np.ndarray[(M * K,), np.dtype[dtype_in]]
    B_ty = np.ndarray[(K * N,), np.dtype[dtype_in]]
    C_ty = np.ndarray[(M * N,), np.dtype[dtype_out]]
    A_l2_ty = np.ndarray[(m * k * n_A_tiles_per_shim,), np.dtype[dtype_in]]
    B_l2_ty = np.ndarray[(k * n,), np.dtype[dtype_in]]
    C_l2_ty = np.ndarray[(m * n * n_aie_rows,), np.dtype[dtype_out]]
    A_l1_ty = np.ndarray[(m, k), np.dtype[dtype_in]]
    B_l1_ty = np.ndarray[(k, n), np.dtype[dtype_in]]
    C_l1_ty = np.ndarray[(m, n), np.dtype[dtype_out]]
    # Core-local f32 accumulator tile (one per worker).
    cacc_ty = np.ndarray[(m, n), np.dtype[dtype_acc]]

    # AIE Core Function declarations. The zero+matmul kernels operate on the f32
    # accumulator (cacc_ty); the epilogue reads f32 acc, writes bf16 out tile.
    zero_kernel = Kernel(f"zero_{dtype_acc_str}", f"mm_{m}x{k}x{n}.o", [cacc_ty])
    matmul_kernel = Kernel(
        f"matmul_{dtype_in_str}_{dtype_acc_str}",
        f"mm_{m}x{k}x{n}.o",
        [A_l1_ty, B_l1_ty, cacc_ty],
    )
    # MODAL f32-out epilogue: rtp[0] selects silu (1) vs identity (0) at runtime, so ONE xclbin
    # serves both via the inst-stream-baked rtp value (the do_silu build flag sets that value below).
    rtp_ty = np.ndarray[(16,), np.dtype[np.int32]]
    epilogue_kernel = Kernel(
        f"mm_modal_epilogue_f32_{dtype_out_str}",
        f"mm_silu_epilogue_{m}x{k}x{n}.o",
        [cacc_ty, C_l1_ty, rtp_ty],
    )

    # MODE 4: resadd, carried as a MODE of this xclbin rather than a sibling one. It reuses the
    # GEMM's own A and B input channels and its C drain -- it declares no fifo of its own, because
    # a second topology cannot route: the GEMM already holds core DMA 2/2, East/South/West 4/4 and
    # memtile DMA 6/6, and two fifos in one excl_group still cost two channels and two routes
    # (see routed-modal-gemm-dest-port-use, excl-group-fifos-dma-channel-cost). The topology is
    # what cannot be duplicated; what flows through it may vary freely.
    if rtp_mode_resadd and not (mode_resadd or resadd_only):
        raise ValueError(
            "--rtp-mode-resadd selects rtp[0]=4, but without --mode-resadd this xclbin has no "
            "mode-4 body: the cores would take the GEMM branch on a stream that never feeds it."
        )
    if resadd_only and mode_resadd:
        raise ValueError(
            "--resadd-only and --mode-resadd are the two arms of the co-residency "
            "discriminator, not a combination: --mode-resadd puts resadd in a core ELF that "
            "also carries the matmul, --resadd-only builds the same body ALONE."
        )
    if mode_read_late and not mode_resadd:
        raise ValueError(
            "--mode-read-late moves the mode-4 branch behind the first A/B acquire, so it "
            "needs --mode-resadd: without a mode-4 body there is no branch to move."
        )
    if k_read_late and not k_loop_rtp:
        raise ValueError(
            "--k-read-late moves the k_trip read behind the first A/B acquire, so it needs "
            "--k-loop-rtp: with a baked K//k there is no runtime read to move."
        )
    if k_read_late and mode_resadd and not mode_read_late:
        raise ValueError(
            "--k-read-late with --mode-resadd needs --mode-read-late too. Otherwise the GEMM "
            "path peels while the is_gemm branch that selects it still reads rtp[0] at the top "
            "of the tile: half the body behind this dispatch's data and half behind the "
            "previous one's. The two peels share one acquire pair -- take both or neither."
        )
    if k_read_late and resadd_only:
        raise ValueError(
            "--k-read-late has nothing to move in --resadd-only: that body carries no matmul, "
            "so its k_trip read is a drain count with no peel to hang it behind."
        )
    resadd_kernel = (
        Kernel(
            "mm_mode_resadd_bf16_f32",
            f"mm_silu_epilogue_{m}x{k}x{n}.o",
            [A_l1_ty, B_l1_ty, C_l1_ty],
        )
        if (mode_resadd or resadd_only)
        else None
    )

    # --mode-lnaffcast: LN + affine + cast as a mode of the BF16-OUT resident. It is the mirror
    # of --mode-resadd's constraint rather than an exception to it -- resadd needs the f32-out
    # path because it borrows the C tile as an accumulator, and this needs the bf16-out path
    # because it needs `cacc` as staging and writes C exactly once, the way the epilogue does.
    #
    # Sizing, all forced by the shipped resident and none of it newly declared: one x row is
    # LNA_COLS f32, an A tile carries m*k/2 f32, and a C tile holds m*n/LNA_COLS output rows.
    # cacc is m*n f32, which is exactly those rows -- the staging buffer already exists.
    lnaff_slabs = 0
    lnaff_stage_kernel = lnaff_apply_kernel = lnaff_apply_x_kernel = None
    if rtp_mode_lnaffcast and not mode_lnaffcast:
        raise ValueError(
            "--rtp-mode-lnaffcast selects the lnaffcast stream, but --mode-lnaffcast=<cols> is "
            "what puts the body in the xclbin. Emitting the stream without the body would bake "
            "a mode value no core can service."
        )
    if mode_lnaffcast:
        if dtype_out_str != "bf16":
            raise ValueError(
                "--mode-lnaffcast needs the bf16-out path (dtype_out=bf16): it stages into the "
                "per-core cacc and writes the C tile once, both of which exist only there. The "
                "f32-out body has no cacc, and its C tile is the live accumulator."
            )
        a_tile_f32 = m * k // 2
        if mode_lnaffcast % a_tile_f32:
            raise ValueError(
                f"--mode-lnaffcast={mode_lnaffcast} (cols) must be a whole number of A tiles: "
                f"an A tile carries m*k/2 = {a_tile_f32} f32 at m={m} k={k}."
            )
        if (m * n) % mode_lnaffcast:
            raise ValueError(
                f"--mode-lnaffcast={mode_lnaffcast} (cols) must divide the C tile's m*n = "
                f"{m * n}, or a C tile would hold a fractional output row."
            )
        # Slabs the mode consumes per C tile. This is ALSO the A fill count its own stream must
        # program -- a mode with its own instruction stream sets its own fill contract and does
        # not inherit the GEMM's k_trip A/B pairing.
        lnaff_slabs = (m * n) // a_tile_f32
        # A ROUND is one C tile per core. The 8 columns of an array row share one A_L2L1 fifo
        # (measured: A_L2L1_0 lists 8 consumer cores in the shipped resident), so they receive
        # the SAME slabs and compute the SAME output rows. A round therefore advances by
        # n_aie_rows blocks, not by the core count, and every output row is written n_aie_cols
        # times. That redundancy is the mode's price on this vehicle, not a bug in the sequence
        # -- see lnaffcast-mode-duplicates-output-across-the-a-broadcast.
        lnaff_rows_per_c = (m * n) // mode_lnaffcast
        lnaff_rows_per_round = lnaff_rows_per_c * n_aie_rows
        # x rides the A tensor as f32-in-bf16, y the C tensor. --lnaffcast-c-fanout gives each
        # column its OWN output region so a probe can read all n_aie_cols copies and check they
        # agree; without it they land on one region and the duplicate writes overwrite.
        lnaff_rows_cap = min(
            M * K // 2 // mode_lnaffcast,
            M * N // mode_lnaffcast // (n_aie_cols if lnaffcast_c_fanout else 1),
        )
        # --lnaffcast-1x: SWAP which operand carries which thing. The duplication above is a
        # property of WHICH fifo x arrives on, not of the mode: A_L2L1 is per-array-row and
        # broadcast across the 8 columns, so x on A makes the columns compute the same rows.
        # gb is a weight and wants exactly that broadcast; x wants the per-column fifo. So x
        # goes on B and gb on A, and the row axis is broken by a SKIP -- a column's B stream
        # carries n_aie_rows C tiles' worth and each core applies only its own share.
        #
        # The skip belongs on B for a size reason, not a taste one: a B tile is k*n/2 f32
        # against an A tile's m*k/2, so one C tile of x is lnaff_b_per_c B tiles against
        # lnaff_slabs A ones, and the skip costs n_aie_rows x that -- 8 acquire pairs per C
        # tile here against the 64 the same skip on A would cost.
        lnaff_b_f32 = k * n // 2
        lnaff_rows_per_b = lnaff_b_f32 // mode_lnaffcast
        lnaff_b_per_c = lnaff_gb_slabs = lnaff_rows_per_col = 0
        if lnaffcast_1x:
            if lnaffcast_c_fanout:
                raise ValueError(
                    "--lnaffcast-1x and --lnaffcast-c-fanout are contradictory: fanout exists "
                    "to READ the n_aie_cols duplicate outputs, and 1x is the route that stops "
                    "producing them. Every core writes distinct rows here."
                )
            if lnaff_b_f32 % mode_lnaffcast or lnaff_rows_per_c % lnaff_rows_per_b:
                raise ValueError(
                    f"--lnaffcast-1x needs a B tile to be a whole number of x rows and a C tile "
                    f"a whole number of B tiles: b={lnaff_b_f32} f32, cols={mode_lnaffcast}, "
                    f"rows/C={lnaff_rows_per_c}, rows/B={lnaff_rows_per_b}"
                )
            # gb is 2*cols f32 (gamma then beta) and now arrives as A tiles, so it must be a
            # whole number of them -- the same divisibility --mode-lnaffcast already demands of
            # an x row, applied to the operand that swapped places with it.
            if (2 * mode_lnaffcast) % a_tile_f32:
                raise ValueError(
                    f"--lnaffcast-1x: gb is 2*{mode_lnaffcast} f32 and must be a whole number "
                    f"of A tiles (m*k/2 = {a_tile_f32} f32)"
                )
            lnaff_b_per_c = lnaff_rows_per_c // lnaff_rows_per_b
            lnaff_gb_slabs = (2 * mode_lnaffcast) // a_tile_f32
            # A round is still ONE C tile per core; what changes is that all n_aie_cores of them
            # are now useful, so the round covers n_aie_cols times the rows it used to.
            lnaff_rows_per_col = lnaff_rows_per_c * n_aie_rows
            lnaff_rows_per_round = lnaff_rows_per_col * n_aie_cols
            # x rides B now and gb rides A, so the cap moves to the B tensor. A holds only gb.
            lnaff_rows_cap = min(K * N // 2 // mode_lnaffcast, M * N // mode_lnaffcast)
            if 2 * mode_lnaffcast > M * K:
                raise ValueError(
                    f"--lnaffcast-1x: gb needs {2 * mode_lnaffcast} f32 in the A tensor, which "
                    f"holds {M * K // 2}"
                )
        if not lnaffcast_rows:
            lnaffcast_rows = (lnaff_rows_cap // lnaff_rows_per_round) * lnaff_rows_per_round
        if lnaffcast_rows % lnaff_rows_per_round:
            raise ValueError(
                f"--lnaffcast-rows={lnaffcast_rows} must be a multiple of the round "
                f"{lnaff_rows_per_round} = {lnaff_rows_per_c} rows/C-tile x {n_aie_rows} rows"
            )
        if lnaffcast_rows > lnaff_rows_cap:
            raise ValueError(
                f"--lnaffcast-rows={lnaffcast_rows} exceeds {lnaff_rows_cap}, what the declared "
                + (
                    f"B ({K * N} bf16) and C ({M * N} bf16)"
                    if lnaffcast_1x
                    else f"A ({M * K} bf16) and C ({M * N} bf16)"
                )
                + f" tensors hold at cols={mode_lnaffcast}"
                + (f" x {n_aie_cols} fanout regions" if lnaffcast_c_fanout else "")
            )
        lnaff_obj = f"mm_mode_lnaffcast_{m}x{k}x{n}.o"
        lnaff_stage_kernel = Kernel(
            "mm_lnaff_stage_f32", lnaff_obj, [A_l1_ty, cacc_ty, np.int32]
        )
        lnaff_apply_kernel = Kernel(
            "mm_lnaff_apply_f32", lnaff_obj, [B_l1_ty, cacc_ty, C_l1_ty]
        )
        if lnaffcast_1x:
            # Same staging kernel -- it copies one A tile into cacc either way, and in the 1x
            # route what it copies is a quarter of gb rather than an eighth of x. Only the apply
            # changes side: it reads x out of the B tile in place, so the 1x route never stages
            # an activation at all.
            lnaff_apply_x_kernel = Kernel(
                "mm_lnaff_apply_x_f32", lnaff_obj, [cacc_ty, B_l1_ty, C_l1_ty, np.int32]
            )

    # --mode-resadd2a: `out = a + scale*b` with BOTH operands on the A fifo. resadd has no weight
    # to absorb a broadcast the way lnaffcast's gb does, so the operands are charged their fifo's
    # broadcast factor in acquires instead -- 2 * n/k tiles per C tile per column, and the pairing
    # is free because ONE index map applies to both (two-activation-mode-broadcast-acquire-cost).
    r2a_j = r2a_per_core = r2a_rounds = 0
    r2a_stage_kernel = r2a_apply_kernel = None
    if rtp_mode_resadd2a and not mode_resadd2a:
        raise ValueError(
            "--rtp-mode-resadd2a bakes rtp[0]=5, but --mode-resadd2a is what puts the body in "
            "the xclbin. The stream would select a mode no core can service."
        )
    if mode_resadd2a and (mode_resadd or resadd_only or mode_lnaffcast):
        raise ValueError(
            "--mode-resadd2a is a second body in the same rtp[0] >= 4 branch as --mode-resadd, "
            "--resadd-only and --mode-lnaffcast. Build one mode per xclbin."
        )
    if mode_resadd2a:
        if dtype_out_str != "f32":
            raise ValueError(
                "--mode-resadd2a needs the f32-out path (dtype_out=f32): it stages `a` into the "
                "C tile and accumulates scale*b on top, and only the f32-out body's C tile is an "
                "accumulator."
            )
        if n % k:
            raise ValueError(
                f"--mode-resadd2a needs n % k == 0: the n/k A tiles spanning a C tile are what "
                f"the drain's base offset indexes (n={n}, k={k})."
            )
        if N != n * n_aie_cols:
            raise ValueError(
                f"--mode-resadd2a covers one column-block sweep per round, so the operand row "
                f"must be exactly n * n_aie_cols wide: N={N}, n * n_aie_cols={n * n_aie_cols}."
            )
        r2a_j = n // k
        r2a_per_core = 2 * r2a_j
        # One round is one C tile per core: n_aie_rows * m output rows, the full N wide.
        r2a_rows_per_round = n_aie_rows * m
        # Both operands live in the A tensor -- a at 0, b at rows*N -- so it is A, not C, that
        # caps the sweep.
        r2a_rows_cap = min(M * K // (2 * N), M)
        if not resadd2a_rows:
            resadd2a_rows = (r2a_rows_cap // r2a_rows_per_round) * r2a_rows_per_round
        if resadd2a_rows % r2a_rows_per_round:
            raise ValueError(
                f"--resadd2a-rows={resadd2a_rows} must be a multiple of the round "
                f"{r2a_rows_per_round} = n_aie_rows * m"
            )
        if resadd2a_rows > r2a_rows_cap:
            raise ValueError(
                f"--resadd2a-rows={resadd2a_rows} exceeds {r2a_rows_cap}, what the A tensor "
                f"({M * K} bf16) holds as two {N}-wide operands"
            )
        r2a_rounds = resadd2a_rows // r2a_rows_per_round
        r2a_obj = f"mm_mode_resadd2a_{m}x{k}x{n}.o"
        r2a_stage_kernel = Kernel(
            "mm_resadd2a_stage_f32", r2a_obj, [A_l1_ty, C_l1_ty, np.int32]
        )
        r2a_apply_kernel = Kernel(
            "mm_resadd2a_apply_f32", r2a_obj, [A_l1_ty, C_l1_ty, np.int32, np.int32]
        )
        # An AIE2 tile has no input channel left for a scale operand, so it travels as its f32
        # bit pattern in an i32 the kernel memcpys back. One build serves every scale.
        r2a_scale_bits = int(
            np.frombuffer(np.float32(resadd2a_scale).tobytes(), dtype=np.int32)[0]
        )

    # Tile declarations as tile[row][col]
    tiles = [[(col, row) for col in range(0, n_aie_cols)] for row in range(0, 6)]
    core_tiles = tiles[2:]

    # AIE-array data movement with object fifos
    A_l3l2_fifos = [None] * n_shim_mem_A
    A_l2l1_fifos = [None] * n_aie_rows

    B_l3l2_fifos = [None] * n_aie_cols
    B_l2l1_fifos = [None] * n_aie_cols

    C_l1l2_fifos = [[None] * n_aie_cols for _ in range(n_aie_rows)]
    C_l2l3_fifos = [None] * n_aie_cols

    # Input A
    for i in range(n_shim_mem_A):
        A_l3l2_fifos[i] = ObjectFifo(A_l2_ty, name=f"A_L3L2_{i}", depth=l3l2_fifo_depth)
        start_row = i * n_A_tiles_per_shim
        stop_row = start_row + n_A_tiles_per_shim
        of_offsets = [m * k * j for j in range(stop_row - start_row)]
        dims_to_stream = [
            [
                (m // r, r * k),
                (k // s, s),
                (r, k),
                (s, 1),
            ]
        ] * (stop_row - start_row)
        a_tmp_fifos = (
            A_l3l2_fifos[i]
            .cons()
            .split(
                of_offsets,
                obj_types=[A_l1_ty] * (stop_row - start_row),
                names=[f"A_L2L1_{row}" for row in range(start_row, stop_row)],
                dims_to_stream=dims_to_stream,
                depths=[ab_fifo_depth] * (stop_row - start_row),
            )
        )

        for j in range(stop_row - start_row):
            A_l2l1_fifos[j + start_row] = a_tmp_fifos[j]

    # Input B
    for col in range(n_aie_cols):
        B_l3l2_fifos[col] = ObjectFifo(B_l2_ty, name=f"B_L3L2_{col}", depth=l3l2_fifo_depth)
        if b_col_maj:
            dims_to_stream = [(n // t, t * k), (k // s, s), (t, k), (s, 1)]
        else:
            dims_to_stream = [(k // s, s * n), (n // t, t), (s, n), (t, 1)]
        B_l2l1_fifos[col] = (
            B_l3l2_fifos[col]
            .cons()
            .forward(
                obj_type=B_l1_ty,
                name=f"B_L2L1_{col}",
                dims_to_stream=dims_to_stream,
                depth=ab_fifo_depth,
            )
        )

        # Output C (bf16). The shim de-shuffle dims are dtype-independent stride
        # tuples (same as the plain matmul) -- they reorder the mmul-blocked tile
        # to row-major on the way to DDR.
        C_l2l3_fifos[col] = ObjectFifo(
            C_l2_ty,
            name=f"C_L2L3_{col}",
            depth=c_fifo_depth,
            dims_to_stream=[(m // r, r * n), (r, t), (n // t, r * t), (t, 1)],
        )
        of_offsets = [m * n * i for i in range(n_aie_rows)]

        c_tmp_fifos = (
            C_l2l3_fifos[col]
            .prod()
            .join(
                of_offsets,
                obj_types=[C_l1_ty] * n_aie_rows,
                names=[f"C_L1L2_{col}_{row}" for row in range(n_aie_rows)],
                depths=[c_fifo_depth] * n_aie_rows,
            )
        )
        for j in range(n_aie_rows):
            C_l1l2_fifos[j][col] = c_tmp_fifos[j]

    # Tasks for each worker to perform. Because the modal output is f32 (same dtype as the f32
    # accumulator), the matmul reduces DIRECTLY into the C output tile and the epilogue runs IN-PLACE
    # on it (silu/identity, f32->f32) — no separate acc_buf. That saves an m*n*4 L1 buffer per core,
    # which is what lets the wide-N fast tile (64x32x96) fit in L1.
    def _minus_one(trip):
        # k_trip is a Python int when K//k is baked and an i32 memref.load under --k-loop-rtp.
        # The peel needs trip-1 either way, so subtract in whichever domain it lives in.
        if isinstance(trip, int):
            return trip - 1
        return _arith.subi(trip, _arith.constant(_T.i32(), 1))

    def core_fn(
        in_a,
        in_b,
        out_c,
        rtp_buff,
        barrier,
        zero,
        matmul,
        epilogue,
        resadd=None,
        r2a_stage=None,
        r2a_apply=None,
        r2a_col=0,
    ):
        barrier.wait_for_value(1)  # wait for the host to write the epilogue mode into rtp
        # k-loop-bound-as-rtp PoC: rtp[1] carries the K-tile trip count, written by sequence()
        # alongside rtp[0]'s epilogue mode, so ONE compiled core body serves any K value --
        # the loop bound is a runtime memref.load, not a Python-baked constant. range_/_for
        # accepts an MLIR Value as the loop stop, and AIESCFToControlFlow lowers it generically,
        # so no toolchain change is needed for this to work.
        loop = range(1)  # Workaround for issue #1547
        if n_tiles_per_core > 1:
            loop = range_(n_tiles_per_core)
        for _ in loop:
            # Load INSIDE the tile loop, matching where rtp[0] is read (the epilogue call below).
            # The core body is an infinite loop whose tile count is baked from the BUILD's N, while
            # a dispatch delivers the STREAM's N worth of tiles -- the two need not align, so one
            # body iteration can span several dispatches whenever stream N < build N. rtp is a
            # side-channel, not fifo-ordered, so anything hoisted above this loop is sampled once
            # per body iteration and pairs with whichever dispatch happened to enter it. That is
            # invisible while every stream shares K=1024, and silently wrong the moment two streams
            # carry different K -- which is the whole point of driving K from rtp.
            # Under --k-read-late every path that reads k_trip does so behind its own acquire,
            # so emitting this load as well would leave a dead top-of-tile read in the IR --
            # exactly the shape a later reader would take for the defect still being present.
            # The plain resadd borrow is the one path that still reads at the top.
            needs_top_read = not k_read_late or (resadd is not None and not mode_read_late)
            k_trip = (rtp_buff[1] if k_loop_rtp else K // k) if needs_top_read else None
            elem_out = out_c.acquire(1)

            def _gemm_path(peeled_a=None):
                zero(elem_out)
                rest = k_trip
                if peeled_a is not None:
                    # The A acquire that got this branch behind rtp is this tile's first, so
                    # finish it here and the trip count still describes the whole tile.
                    eb = in_b.acquire(1)
                    rest = _minus_one(rtp_buff[1] if k_read_late else k_trip)
                    matmul(peeled_a, eb, elem_out)
                    in_a.release(1)
                    in_b.release(1)
                elif k_read_late:
                    # PEEL, for the same reason --mode-read-late peels: a top-of-tile rtp read
                    # samples the PREVIOUS dispatch's value. A stale K is worse than a stale
                    # epilogue mode -- the trip count decides how many A/B pairs this tile
                    # consumes, so one wrong read desynchronises the fifos for everything after,
                    # which is why mixed-K failures have no clean recurrence. Reading behind the
                    # first acquire puts it downstream of this dispatch's own data.
                    ea = in_a.acquire(1)
                    eb = in_b.acquire(1)
                    rest = _minus_one(rtp_buff[1])
                    matmul(ea, eb, elem_out)
                    in_a.release(1)
                    in_b.release(1)
                for _ in range_(rest):
                    elem_in_a = in_a.acquire(1)
                    elem_in_b = in_b.acquire(1)
                    matmul(elem_in_a, elem_in_b, elem_out)
                    in_a.release(1)
                    in_b.release(1)
                epilogue(elem_out, elem_out, rtp_buff)  # in-place; rtp[0]: 1=silu, 0=identity

            def _is_gemm():
                # rtp[0] < 4 keeps the GEMM (its own four epilogue modes); 4 is resadd.
                return _arith.cmpi(
                    _arith.CmpIPredicate.slt,
                    rtp_buff[0],
                    _arith.constant(_T.i32(), 4),
                )

            def _drain_ab(trip, fn):
                for _ in range_(trip):
                    ea = in_a.acquire(1)
                    eb = in_b.acquire(1)
                    fn(ea, eb, elem_out)
                    in_a.release(1)
                    in_b.release(1)

            if resadd is None and r2a_stage is None:
                _gemm_path()
            elif r2a_stage is not None:
                # Peel ONE A acquire and branch behind it: rtp has a measured one-tile
                # visibility lag, so a top-of-tile read runs the previous dispatch's body on
                # each core's first tile. Only A is peeled -- this mode consumes no B, and its
                # own stream programs no B fill to acquire.
                ea = in_a.acquire(1)
                if k_read_late:
                    k_trip = rtp_buff[1]
                with scf_if_(_is_gemm()) as if_op:
                    _gemm_path(peeled_a=ea)
                with scf_else_(if_op):
                    # The row's A stream carries every column's share, because A_L2L1 is
                    # broadcast across the columns of an array row; a core acquires all of them
                    # and applies the r2a_per_core that are its own. Python-unrolled, so the
                    # skip and the slab index are compile-time constants and cost no branch.
                    for slot in range(n_aie_cols * r2a_per_core):
                        elem_in_a = ea if slot == 0 else in_a.acquire(1)
                        if slot // r2a_per_core == r2a_col:
                            local = slot % r2a_per_core
                            if local < r2a_j:
                                r2a_stage(elem_in_a, elem_out, local)
                            else:
                                r2a_apply(
                                    elem_in_a, elem_out, local - r2a_j, r2a_scale_bits
                                )
                        in_a.release(1)
            elif mode_read_late:
                # ORDERING ARM. rtp is a side-channel with a MEASURED one-tile visibility lag:
                # barrier.wait_for_value sits outside the tile loop, so it orders only a
                # context's first dispatch and a read at the TOP of a tile samples the PREVIOUS
                # dispatch's mode -- each core's first tile runs the wrong body, every later tile
                # the right one. The epilogue escapes it only by reading after the k-loop. So
                # peel the first A/B pair and branch behind that acquire, which this dispatch's
                # own data has to cross. Under test: whether ONE acquire is late enough.
                # See 2026-08-22-the-mode-swap-costs-one-tile-and-then-recovers.
                elem_in_a = in_a.acquire(1)
                elem_in_b = in_b.acquire(1)
                if k_read_late:
                    k_trip = rtp_buff[1]  # behind the same acquire the mode branch is
                with scf_if_(_is_gemm()) as if_op:
                    zero(elem_out)
                    matmul(elem_in_a, elem_in_b, elem_out)
                    in_a.release(1)
                    in_b.release(1)
                    _drain_ab(_minus_one(k_trip), matmul)
                    epilogue(elem_out, elem_out, rtp_buff)
                with scf_else_(if_op):
                    resadd(elem_in_a, elem_in_b, elem_out)
                    in_a.release(1)
                    in_b.release(1)
                    _drain_ab(_minus_one(k_trip), resadd)
            else:
                # The two bodies must sit in DIFFERENT regions of one scf.if, not merely
                # different blocks: that is what makes them mutually exclusive to the excl_group
                # core-reference check, and it is what the check was sharpened to admit.
                is_gemm = _is_gemm()
                with scf_if_(is_gemm) as if_op:
                    _gemm_path()
                with scf_else_(if_op):
                    # Borrows A and B and drains through C -- no fifo of its own. A mode that
                    # borrows a topology also inherits its STREAM CONTRACT: the GEMM's stream
                    # delivers k_trip A/B tile pairs per output tile, so this must consume all
                    # k_trip or the fifos stall and nothing drains (measured: a body consuming
                    # one pair returned an all-zero C). resadd uses the FIRST pair and drains
                    # the rest, which is why the add is peeled out of the loop instead of
                    # sitting under a conditional inside it.
                    for _ in range_(k_trip):
                        elem_in_a = in_a.acquire(1)
                        elem_in_b = in_b.acquire(1)
                        resadd(elem_in_a, elem_in_b, elem_out)
                        in_a.release(1)
                        in_b.release(1)
            out_c.release(1)

    def core_fn_resadd_only(in_a, in_b, out_c, rtp_buff, barrier, resadd):
        # Discriminator arm for the mode-4 hang: the SAME resadd body, the same stream contract
        # and the same shapes, in a core ELF that does NOT carry the matmul. Completing here
        # implicates two-body co-residency; hanging here implicates the operator itself.
        barrier.wait_for_value(1)
        loop = range(1)  # Workaround for issue #1547
        if n_tiles_per_core > 1:
            loop = range_(n_tiles_per_core)
        for _ in loop:
            k_trip = rtp_buff[1] if k_loop_rtp else K // k
            elem_out = out_c.acquire(1)
            # Drains all k_trip pairs, same as the mode arm: the borrowed topology's stream
            # contract is a property of the STREAM, not of which body reads it.
            for _ in range_(k_trip):
                elem_in_a = in_a.acquire(1)
                elem_in_b = in_b.acquire(1)
                resadd(elem_in_a, elem_in_b, elem_out)
                in_a.release(1)
                in_b.release(1)
            out_c.release(1)

    # bf16-out sibling: the matmul reduces f32, so it CANNOT reduce into a bf16 C tile. This
    # variant keeps a core-local f32 accumulator and the epilogue narrows acc -> C on the way
    # out. That costs an extra m*n*4 L1 buffer per core, which is exactly the buffer the f32-out
    # modal deleted to make the wide-N fast tile fit -- so a bf16-out build has a tighter L1
    # budget and may need a smaller m. The allocator, not this comment, is the authority.
    def core_fn_split_acc(
        in_a,
        in_b,
        out_c,
        acc,
        rtp_buff,
        barrier,
        zero,
        matmul,
        epilogue,
        lnaff_stage=None,
        lnaff_apply=None,
        lnaff_apply_x=None,
        lnaff_row=0,
    ):
        barrier.wait_for_value(1)
        loop = range(1)  # Workaround for issue #1547
        if n_tiles_per_core > 1:
            loop = range_(n_tiles_per_core)
        for _ in loop:
            # Inside the tile loop, for the same reason as core_fn above: a body iteration can
            # span several dispatches, so a hoisted rtp read pairs with the wrong one.
            k_trip = None if k_read_late else (rtp_buff[1] if k_loop_rtp else K // k)
            elem_out = out_c.acquire(1)

            def _gemm_path(peeled_a=None):
                zero(acc)
                rest = k_trip
                if peeled_a is not None:
                    # The A pair was already taken to get behind rtp (see below); finish it
                    # here so the trip count and the fifo balance both still describe the
                    # whole tile.
                    eb = in_b.acquire(1)
                    rest = _minus_one(rtp_buff[1] if k_read_late else k_trip)
                    matmul(peeled_a, eb, acc)
                    in_a.release(1)
                    in_b.release(1)
                elif k_read_late:
                    # Same peel as core_fn's GEMM path, and this is the body the mixed-K
                    # failure was measured on (bf16 out). See the comment there for why a
                    # stale k_trip desynchronises the fifos rather than merely mis-computing
                    # one tile.
                    ea = in_a.acquire(1)
                    eb = in_b.acquire(1)
                    rest = _minus_one(rtp_buff[1])
                    matmul(ea, eb, acc)
                    in_a.release(1)
                    in_b.release(1)
                for _ in range_(rest):
                    elem_in_a = in_a.acquire(1)
                    elem_in_b = in_b.acquire(1)
                    matmul(elem_in_a, elem_in_b, acc)
                    in_a.release(1)
                    in_b.release(1)
                epilogue(acc, elem_out, rtp_buff)  # f32 acc -> bf16 C; rtp[0] selects the mode

            if lnaff_apply is None:
                _gemm_path()
            else:
                # PEEL ONE A ACQUIRE AND BRANCH BEHIND IT, for the reason --mode-read-late
                # peels on the f32-out side: rtp is a side-channel with a MEASURED one-tile
                # visibility lag, so a branch on a top-of-tile read runs the PREVIOUS
                # dispatch's body on each core's first tile. One acquire of this dispatch's
                # own data is enough -- measured on the K read, which is the stricter case
                # (see k-read-after-first-acquire-fixes-mixed-k).
                #
                # Only A is peeled. The GEMM takes its B inside the branch, and lnaffcast
                # takes exactly one B at the END: gb is a per-row weight, not a per-slab
                # operand, so pairing it with A the way the GEMM does would make its own
                # stream fill B lnaff_slabs times for one tile's worth of use.
                ea = in_a.acquire(1)
                with scf_if_(
                    # rtp[0] < 4 is the GEMM and its four epilogue modes, the same split the
                    # f32-out body uses. A bf16-out build carries at most this one mode, so
                    # every value at or above 4 lands here.
                    _arith.cmpi(
                        _arith.CmpIPredicate.slt,
                        rtp_buff[0],
                        _arith.constant(_T.i32(), 4),
                    )
                ) as if_op:
                    _gemm_path(peeled_a=ea)
                with scf_else_(if_op):
                    # Python-unrolled, so each slot is a compile-time constant: the mode needs
                    # no core-side counter and no loop-index cast to address its slab.
                    if lnaff_apply_x is None:
                        lnaff_stage(ea, acc, 0)
                        in_a.release(1)
                        for slot in range(1, lnaff_slabs):
                            elem_in_a = in_a.acquire(1)
                            lnaff_stage(elem_in_a, acc, slot)
                            in_a.release(1)
                        elem_in_b = in_b.acquire(1)
                        lnaff_apply(elem_in_b, acc, elem_out)
                        in_b.release(1)
                    else:
                        # THE 1x ROUTE. A now carries gb, so the peeled acquire that gets this
                        # branch behind rtp is gb's first slab rather than x's -- the peel is
                        # about ORDER, not about which operand, so it survives the swap.
                        lnaff_stage(ea, acc, 0)
                        in_a.release(1)
                        for slot in range(1, lnaff_gb_slabs):
                            elem_in_a = in_a.acquire(1)
                            lnaff_stage(elem_in_a, acc, slot)
                            in_a.release(1)
                        # x arrives on the column's B fifo, which is broadcast down the
                        # n_aie_rows cores of the column, so EVERY core must consume every tile
                        # for the fifo to advance. Each applies only the lnaff_b_per_c tiles
                        # that are its own; the rest are an acquire/release pair and touch no
                        # data. The share is a Python constant, so the skip costs no branch.
                        for j in range(lnaff_b_per_c * n_aie_rows):
                            elem_in_b = in_b.acquire(1)
                            if j // lnaff_b_per_c == lnaff_row:
                                lnaff_apply_x(
                                    acc,
                                    elem_in_b,
                                    elem_out,
                                    (j % lnaff_b_per_c) * lnaff_rows_per_b,
                                )
                            in_b.release(1)
            out_c.release(1)

    # Per-core RTP (epilogue mode) + a shared runtime barrier. Each worker reads rtp[0].
    rtp_barrier = WorkerRuntimeBarrier()
    rtp_bufs = [
        [
            Buffer(rtp_ty, name=f"rtp_{row}_{col}", use_write_rtp=True)
            for col in range(n_aie_cols)
        ]
        for row in range(n_aie_rows)
    ]

    # Set up compute tiles. f32 out: in-place modal epilogue -> no per-core acc_buf (the matmul
    # reduces straight into C). bf16 out: a per-core f32 accumulator, narrowed by the epilogue.
    split_acc = dtype_out_str != dtype_acc_str
    workers = []
    for row in range(n_aie_rows):
        for col in range(n_aie_cols):
            args = [
                A_l2l1_fifos[row].cons(),
                B_l2l1_fifos[col].cons(),
                C_l1l2_fifos[row][col].prod(),
            ]
            if split_acc:
                args.append(Buffer(cacc_ty, name=f"cacc_{row}_{col}"))
            if resadd_only:
                # zero/matmul/epilogue are deliberately NOT referenced: an unreferenced Kernel
                # is never declared, so the matmul stays out of the core ELF entirely. That
                # absence IS the experiment.
                if split_acc:
                    raise ValueError(
                        "--resadd-only needs the f32-out path (dtype_out=f32), same as "
                        "--mode-resadd: the bf16-out body has no C tile to write into."
                    )
                args += [rtp_bufs[row][col], rtp_barrier, resadd_kernel]
                workers.append(
                    Worker(
                        core_fn_resadd_only, args, stack_size=_stack_size()
                    )
                )
                continue
            args += [
                rtp_bufs[row][col],
                rtp_barrier,
                zero_kernel,
                matmul_kernel,
                epilogue_kernel,
            ]
            if resadd_kernel is not None:
                # Only the f32-out body carries the mode; the bf16-out sibling reduces into a
                # core-local acc and has no C tile to hand a mode kernel.
                if split_acc:
                    raise ValueError(
                        "--mode-resadd needs the f32-out path (dtype_out=f32): the bf16-out "
                        "body accumulates into a core-local buffer, so a mode borrowing the C "
                        "tile has nothing to write into."
                    )
                args.append(resadd_kernel)
            if lnaff_apply_kernel is not None:
                # bf16-out only, checked at declaration; split_acc is that condition.
                args += [lnaff_stage_kernel, lnaff_apply_kernel]
            body = core_fn_split_acc if split_acc else core_fn
            if r2a_stage_kernel is not None:
                args += [r2a_stage_kernel, r2a_apply_kernel]
                # The COLUMN picks which share of the row's A stream this core applies. Bound in
                # a closure because fn_args are core arguments and a Python int is not one. The
                # two mode kernels are passed by NAME: `resadd` sits between them and the
                # epilogue in the signature, and this mode never carries it.
                def body(*fn_args, _col=col):
                    return core_fn(
                        *fn_args[:8],
                        r2a_stage=fn_args[8],
                        r2a_apply=fn_args[9],
                        r2a_col=_col,
                    )

            if lnaff_apply_x_kernel is not None:
                args.append(lnaff_apply_x_kernel)
                # The array row picks which share of the column's B stream this core applies.
                # It is bound in a closure rather than appended to args because fn_args are
                # registered as CORE arguments and a Python int is not one -- and the body is
                # traced inline per tile (Worker calls core_fn inside @core), so a per-row
                # closure costs nothing and needs no distinct name.
                def body(*fn_args, _row=row):
                    return core_fn_split_acc(*fn_args, lnaff_row=_row)

            workers.append(Worker(body, args, stack_size=_stack_size()))

    tb_max_n_rows = 4
    # DERIVED, not `tb_max_n_rows // 2`: the C tiler below asks for exactly this many row-blocks, so a
    # bare 2 forces M % (2 * m * n_aie_rows) == 0 -- i.e. M % 512 == 0 for the shipped 64x32x128 tile.
    # That constraint is what makes PAD_M 512 and leaves 66-90% of every modal GEMM's rows as padding
    # at the encoder's T=52..172. The RUNTIME loop already clamps the same quantity
    # (`min(tb_max_n_rows // 2, M // m // n_aie_rows - row_base)`), so the tiler was the only place
    # assuming two blocks exist.
    tb_n_rows = min(tb_max_n_rows // 2, M // m // n_aie_rows)

    A_tiles = TensorTiler2D.group_tiler(
        (M, K),
        (m * n_A_tiles_per_shim, k),
        (1, K // k),
        pattern_repeat=N // n // n_aie_cols,
        prune_step=False,
    )
    if a_panel_width:
        # Read A straight out of the producer's [K//W, M, W] panel-major buffer (fc1's
        # default bf16 drain), so a wide-K GEMM needs no repack. Insts-only, same as the
        # C-side panel drain.
        A_tiles = panel_major_a_taps(
            A_tiles, M, K, N, m * n_A_tiles_per_shim, k, n_aie_cols, n, a_panel_width
        )
    if b_col_maj:
        B_tiles = TensorTiler2D.step_tiler(
            (N, K),
            (n, k),
            tile_group_repeats=(N // n // n_aie_cols, K // k),
            tile_group_steps=(n_aie_cols, 1),
            prune_step=False,
        )
    else:
        B_tiles = TensorTiler2D.step_tiler(
            (K, N),
            (k, n),
            tile_group_repeats=(K // k, N // n // n_aie_cols),
            tile_group_steps=(1, n_aie_cols),
            tile_group_col_major=True,
            prune_step=False,
        )
    C_tiles = TensorTiler2D.step_tiler(
        (M, N),
        (m * n_aie_rows, n),
        tile_group_repeats=(tb_n_rows, N // n // n_aie_cols),
        tile_group_steps=(1, n_aie_cols),
        prune_step=False,
    )
    if c_panel_width:
        # Drain C straight into the [N//c_panel_width, M, c_panel_width] panel-major layout
        # the consumer wants. Insts-only: same rank/sizes/order, new strides.
        C_tiles = panel_major_c_taps(
            C_tiles, M, N, m, n, n_aie_rows, n_aie_cols, c_panel_width
        )
    c_index = 0

    def lnaffcast_fills(A, B, C, A_prods, B_prods, C_conses):
        """The lnaffcast mode's own fill contract: 8 A + 1 B + 1 C drain per C tile.

        The GEMM's contract is K//k A/B PAIRS per C tile; this body consumes lnaff_slabs A and
        exactly one B, so inheriting the GEMM stream programs 32 A and 32 B fills against 8 and 1
        and stalls the producer on backpressure. Same failure the 2026-08-16 pass predicted.

        Every shuffle is undone on the DDR side, so the core stages, reduces and writes
        CONTIGUOUSLY -- see lnaffcast-mode-taps-fit-the-shim-in-four-dims for the search. Each of
        the three taps is at exactly the shim's 4 dimensions, and A is at 4 only because its
        per-slab dimension merges with the leading permutation digit (512 == 4 x 128), which is a
        property of THIS slab size and does not survive a change to it. That is why the guard
        below is exact rather than a range: these are derived numbers, and a config they were not
        derived for must fail loud instead of emitting a wrong walk.
        """
        if (m, k, n, r, s, t, mode_lnaffcast) != (32, 32, 128, 8, 8, 8, 1024):
            raise ValueError(
                "the lnaffcast taps are derived for the shipped resident "
                f"(m,k,n=32,32,128 r=s=t=8 cols=1024), not (m,k,n={m},{k},{n} "
                f"r,s,t={r},{s},{t} cols={mode_lnaffcast})"
            )
        # f32-derived walks, doubled into the bf16 element units the tensors are declared in.
        # The doubling costs no dimension: the innermost f32 run of 4 at stride 1 becomes 4 at
        # stride 2 with a pair of stride 1 inside it, i.e. 8 contiguous bf16.
        a_sizes, a_strides = [32, 8, 4, 8], [256, 8, 64, 1]     # 8 slabs = one C tile of x
        b_sizes, b_strides = [4, 8, 16, 8], [1024, 8, 64, 1]    # gb = [gamma|beta], 2048 f32
        # C is bf16 already. The outer walk over the n_aie_rows tiles the memtile joins merges
        # into the leading digit (4 x 1024 == the 4-row stride), so one drain covers the round's
        # whole n_aie_rows * lnaff_rows_per_c block of consecutive output rows.
        c_sizes, c_strides = [16, 8, 16, 8], [1024, 8, 64, 1]

        if lnaffcast_1x:
            # The operands swapped sides, and the WALKS follow them unchanged -- what a tap
            # undoes is its fifo's L2->L1 shuffle, which is a property of the fifo, not of what
            # rides it. So the 1x taps are the same two walks above at new counts and offsets:
            #
            #   one A tile  = [4, 8, 4, 8] / [256, 8, 64, 1]   over 1024 contiguous bf16
            #   one B tile  = [4, 8, 16, 8] / [1024, 8, 64, 1] over 4096 contiguous bf16
            #
            # and consecutive tiles merge into the LEADING digit rather than adding a dimension
            # (1024 == 4 x 256, 4096 == 4 x 1024), which is the same merge the 8x A tap already
            # relies on and is why all three still fit the shim's 4 dims.
            a_sizes = [4 * lnaff_gb_slabs, 8, 4, 8]             # gb, now on A
            b_sizes = [4 * lnaff_b_per_c * n_aie_rows, 8, 16, 8]  # x, one column's share

        # --lnaffcast-contig-taps: originally the TIMING-ONLY control for
        # lnaffcast-mode-taps-burst-at-16-bytes. Each named tap keeps its sizes, its offset and
        # its footprint and gets the contiguous strides for those sizes, which raises the
        # innermost run from 8 bf16 to the whole 4096-16384 elements. Sizes are unchanged
        # deliberately: the burst-length claim is that the same byte count at the same rank
        # costs less when it is not scattered, so anything else moving would confound it.
        #
        # WHETHER THE ARM IS CORRECT DEPENDS ON THE CORE BODY, which this generator cannot see.
        # Against the default body the walk is WRONG -- the un-permute is what the real strides
        # encode -- so the arm reads out garbage and is comparable on wall clock alone. Against
        # a body built with LNA_SCATTER_C=1 the core writes C scattered and `c` here is the
        # CORRECT tap for it; the two are one decision and either half alone permutes the
        # output.
        if lnaffcast_contig_taps:
            unknown = set(lnaffcast_contig_taps) - set("abc")
            if unknown:
                raise ValueError(
                    f"--lnaffcast-contig-taps: unknown tap(s) {sorted(unknown)}, expected a "
                    "subset of 'abc'"
                )

            def contiguous(sizes, strides):
                got = [sizes[1] * sizes[2] * sizes[3], sizes[2] * sizes[3], sizes[3], 1]
                span = lambda st: sum((s - 1) * d for s, d in zip(sizes, st))
                if span(got) != span(strides):
                    raise ValueError(
                        f"contiguous restride of {sizes} spans {span(got)} against the real "
                        f"walk's {span(strides)} -- not the same footprint, so it is not a control"
                    )
                return got

            if "a" in lnaffcast_contig_taps:
                a_strides = contiguous(a_sizes, a_strides)
            if "b" in lnaffcast_contig_taps:
                b_strides = contiguous(b_sizes, b_strides)
            if "c" in lnaffcast_contig_taps:
                c_strides = contiguous(c_sizes, c_strides)

        cols = mode_lnaffcast
        c_region = lnaffcast_rows * cols if lnaffcast_c_fanout else 0

        # How many rounds share a TaskGroup. `tg.finish()` is a HOST-side await, so one per round
        # serialises the whole sequence at the round boundary -- the GEMM finishes twice for a
        # 512x1024x1024, not once per tile-block, for exactly this reason. Groups larger than one
        # round let the queue run ahead; the ceiling is BD/queue resource, not correctness.
        rounds = lnaffcast_rows // lnaff_rows_per_round
        tg = None
        for rnd in range(rounds):
            base = rnd * lnaff_rows_per_round
            if rnd % lnaffcast_group_rounds == 0:
                tg = TaskGroup()
            for col in range(n_aie_cols):
                # 8x: every column drains the SAME rows (they computed the same thing), so the
                # offset does not move with col and --lnaffcast-c-fanout is what separates them
                # to be read. 1x: a column owns lnaff_rows_per_col consecutive rows, and its
                # n_aie_rows cores split them, so the SAME drain walk lands at a col offset.
                col_base = base + (col * lnaff_rows_per_col if lnaffcast_1x else 0)
                tap_c = TensorAccessPattern(
                    (M * N,), col * c_region + col_base * cols, c_sizes, c_strides
                )
                C_taps.append(tap_c)
                C_conses[col].drain(C, tap=tap_c, wait=True, group=tg)

                # 8x: B is gb, one tile, identical for every column. 1x: B is x, and this is
                # the fifo the whole route turns on -- per column, so the columns diverge.
                tap_b = TensorAccessPattern(
                    (K * N,), col_base * cols * 2 if lnaffcast_1x else 0, b_sizes, b_strides
                )
                B_taps.append(tap_b)
                B_prods[col].fill(B, tap=tap_b, group=tg)

            for row in range(n_aie_rows):
                # 8x: A is x, one C tile's worth per array row. 1x: A is gb -- the same bytes
                # to every row, which is what the broadcast is for and why the offset is 0.
                tap_a = TensorAccessPattern(
                    (M * K,),
                    0 if lnaffcast_1x else (base + row * lnaff_rows_per_c) * cols * 2,
                    a_sizes,
                    a_strides,
                )
                A_taps.append(tap_a)
                A_prods[row].fill(A, tap=tap_a, group=tg)
            if rnd % lnaffcast_group_rounds == lnaffcast_group_rounds - 1 or rnd == rounds - 1:
                tg.finish()

    def resadd2a_fills(A, B, C, A_prods, B_prods, C_conses):
        """The mode's own fill contract: n_aie_cols * 2 * n/k A tiles per array row, 1 C drain
        per column, no B.

        Both operands live in the A tensor as [rows, N] bf16 -- a at 0, b at rows*N -- so the
        taps are plain row-major [m, k] block reads and the C drain is the row-major block the
        GEMM already uses. Nothing here undoes a fifo shuffle: the core writes L1 C at the
        address the drain reads it from, which the closed form in mm_mode_resadd2a.cc computes
        from the tile dims.

        Stream order is a core's whole share back to back -- its n/k `a` tiles, then its n/k
        `b` tiles -- because the body stages all of `a` into the C tile before accumulating
        onto it, and the fifo is the only thing that orders them.
        """
        op_stride = resadd2a_rows * N
        # Which end of the column the sequence fills FIRST. A hung dispatch drains a PREFIX of the
        # array rows -- rows 0-1 complete and bit-exact, rows 2-3 untouched, uniform across all 8
        # columns -- and row 0 is the core tile nearest the memtile. Reversing this loop separates
        # the two explanations that shape admits: if the surviving prefix follows the FILL ORDER it
        # is a programming/BD-order effect, and if it stays at rows 0-1 it is routing or service
        # order down the column. Nothing else changes -- same taps, same count, same array program.
        row_order = list(range(n_aie_rows))
        if resadd2a_rev_rows:
            row_order = row_order[::-1]
        for rnd in range(r2a_rounds):
            row_base = rnd * n_aie_rows * m
            # One TaskGroup per COLUMN's share, because a shim tile holds 16 active BDs and a
            # round programs n_aie_cols * 2 * n/k = 64 A fills onto each. The C drains cannot
            # ride these groups: a core releases its C tile only after the LAST column's share,
            # so awaiting a drain before the sequence has issued the rest would deadlock.
            for col in range(n_aie_cols):
                tg = TaskGroup()
                for row in row_order:
                    for operand in range(2):
                        for j in range(r2a_j):
                            tap_a = TensorAccessPattern(
                                (M * K,),
                                operand * op_stride
                                + (row_base + row * m) * N
                                + col * n
                                + j * k,
                                [m, k],
                                [N, 1],
                            )
                            A_taps.append(tap_a)
                            A_prods[row].fill(A, tap=tap_a, group=tg)
                tg.finish()

            tg = TaskGroup()
            for col in range(n_aie_cols):
                tap_c = TensorAccessPattern(
                    (M * N,),
                    row_base * N + col * n,
                    [n_aie_rows * m, n],
                    [N, 1],
                )
                C_taps.append(tap_c)
                C_conses[col].drain(C, tap=tap_c, wait=True, group=tg)
            tg.finish()

    def sequence(A, B, C, A_prods, B_prods, C_conses):
        nonlocal c_index
        # bake the epilogue mode into this instruction stream's RTP (1=silu, 0=identity), then
        # release the barrier so the cores read it. A silu-built stream and an identity-built stream
        # are two .txt insts on the SAME xclbin -> the host picks mode by choosing the stream.
        # rtp[0]: 0=identity, 1=silu, 2=gelu, 3=glu. GLU halves the LIVE output width (it writes
        # into the value half of each tile and leaves the accumulator in the gate half), but the
        # drain stays FULL width -- a narrower tap would change the TAP SIZES, and the insts-only
        # property holds only for a re-stride at constant sizes. The consumer reads the strided
        # subset instead. So no tap change here, deliberately.
        # rtp_mode_resadd bakes 4 instead, which is the whole point of the mode: the ARRAY
        # PROGRAM is the same either way, so the resadd arm and the GEMM arm are two insts
        # streams on ONE xclbin -- the host picks the op by choosing the stream, at no
        # program transition. Same mechanism the id/silu pair already ships on.
        # 18 is the lnaffcast mode. It sits above resadd's 4 rather than reusing it so a stream
        # cannot select the wrong family on a build that carries both bodies -- the core only
        # tests `< 4`, but the VALUE is what a dispatch log and a bisect arm read.
        mode_val = (
            18
            if rtp_mode_lnaffcast
            else (
                5
                if rtp_mode_resadd2a
                else (
                    4
                    if rtp_mode_resadd
                    else (3 if do_glu else (2 if do_gelu else (1 if do_silu else 0)))
                )
            )
        )
        for r in range(n_aie_rows):
            for c in range(n_aie_cols):
                rtp_bufs[r][c][0] = mode_val
                if k_loop_rtp:
                    rtp_bufs[r][c][1] = K // k  # k-loop-bound-as-rtp PoC: K-tile trip count
        rtp_barrier.set(1)

        if rtp_mode_lnaffcast:
            lnaffcast_fills(A, B, C, A_prods, B_prods, C_conses)
            return

        if rtp_mode_resadd2a:
            resadd2a_fills(A, B, C, A_prods, B_prods, C_conses)
            return

        tg = TaskGroup()
        for tb in range(ceildiv(M // m // n_aie_rows, tb_max_n_rows)):
            for pingpong in [0, 1]:
                if c_index >= len(C_tiles):
                    break

                row_base = tb * tb_max_n_rows + pingpong * tb_max_n_rows // 2
                current_tb_n_rows = min(
                    [tb_max_n_rows // 2, M // m // n_aie_rows - row_base]
                )

                for col in range(n_aie_cols):
                    C_taps.append(C_tiles[c_index])
                    C_conses[col].drain(
                        C,
                        tap=C_tiles[c_index],
                        wait=True,
                        group=tg,
                    )
                    c_index += 1

                    for tile_row in range(current_tb_n_rows):
                        tile_offset = (
                            (row_base + tile_row) * n_shim_mem_A + col
                        ) % len(A_tiles)

                        if col < n_aie_rows:
                            A_prods[col].fill(
                                A,
                                tap=A_tiles[tile_offset],
                                group=tg,
                            )

                        B_prods[col].fill(
                            B,
                            tap=B_tiles[col],
                            group=tg,
                        )

                        A_taps.append(A_tiles[tile_offset])
                        B_taps.append(B_tiles[col])
                if tb > 0 or (tb == 0 and pingpong > 0):
                    tg.finish()
                    tg = TaskGroup()
        tg.finish()

    rt = Runtime(
        sequence,
        [
            A_ty,
            B_ty,
            C_ty,
            [f.prod() for f in A_l3l2_fifos],
            [f.prod() for f in B_l3l2_fifos],
            [f.cons() for f in C_l2l3_fifos],
        ],
    )

    my_program = Program(dev_ty, rt, workers=workers)
    # Per-op occupancy instrument. `trace_size=0` (production) leaves the design byte-identical.
    # Trace ONE worker: every worker runs the identical tile loop, so one is representative.
    #
    # WHICH worker is not free. A core tile has 4 South egress ports and, in column 0, no West;
    # this design sends every core's C stream downward, so the bottom tile carries its own C plus
    # the rows above it. Measured 2026-08-17 on the pinned toolchain (N=1024, m/k/n 64/32/128,
    # WA_C_DEPTH=1), cols=1 South-out usage is (0,2) 4/4, (0,3) 3/4, (0,4) 2/4, (0,5) 1/4 -- so
    # tracing workers[0] at row 2 has nowhere to go and the packet never leaves the tile. That is
    # why no destination-side lever moves it: lateral-routing and egress_shim_col 0/1/4 all fail
    # identically. Tracing a HIGHER row routes.
    #
    # By width: cols=4 builds green (verified through aiecc, not just the pathfinder) with any
    # worker; cols=1 needs worker >= 1; cols=8 does not route at any worker or egress column,
    # because its production routing already pins (0,2) and (0,4) at 4/4. Getting cols=8 traced
    # needs fewer downward C streams per column, not a flag.
    #
    # WHICH events is also not free: AIE2 gives 8 per core, so the default set below buys the
    # stall question and pays for it with everything else. MEASURED on device 2026-08-17 at
    # cols=4: it accounts for 33.05% of the traced span (23.44% vector issue + 9.61% stall),
    # and the other 66.95% is dark because no scalar/load-store event is in the set -- not
    # because the core is idle. Pass --trace_events to re-spend the eight slots, keeping
    # INSTR_VECTOR as the anchor that lets two runs be composed.
    # A MEMTILE can be traced too, and it is the only place the two feeds are visible at their
    # SOURCE: A leaves on memtile MM2S ch0, B on ch1. A core trace can only say which feed the core
    # waited on -- it cannot say whether that feed was late because the memtile could not push it
    # (array backpressure), had nothing to push (L3 starvation), or had no free buffer (lock).
    # trace_memtile names the memtile by the B_L2L1 fifo it produces, i.e. by ROW, because that is
    # the axis the binding feed splits on; which A column it also carries is a PLACEMENT fact and
    # must be read back from the IR, not assumed.
    trace_tiles = None
    memtile_events = None
    if trace_size and trace_memtile >= 0:
        b_fifo = B_l2l1_fifos[trace_memtile]
        prod = getattr(b_fifo, "_prod", None)
        if prod is None or prod.endpoint is None or prod.endpoint.tile is None:
            raise ValueError(
                f"B_L2L1_{trace_memtile} has no resolved producer tile to trace"
            )
        trace_tiles = [prod.endpoint.tile]
        if trace_memtile_events:
            memtile_events = [
                _memtile_trace_event(e)
                for e in trace_memtile_events.split(",")
                if e.strip()
            ]
            if len(memtile_events) > 8:
                raise ValueError(
                    f"AIE2 traces 8 memtile events; got {len(memtile_events)}"
                )
    if trace_size:
        events = None
        if trace_events:
            events = [_trace_event(e) for e in trace_events.split(",") if e.strip()]
            if len(events) > 8:
                raise ValueError(f"AIE2 traces 8 core events; got {len(events)}")
        my_program.enable_trace(
            trace_size=trace_size,
            workers=[workers[trace_worker]],
            egress_shim_col=0,
            coretile_events=events,
            trace_tiles=trace_tiles,
            memtile_events=memtile_events,
        )
    # seq_fn now runs at resolve time, so the tap lists are only populated after
    # this call -- generate_taps must return AFTER it, not before.
    module = my_program.resolve_program()

    if generate_taps:
        return (
            TensorAccessSequence.from_taps(A_taps),
            TensorAccessSequence.from_taps(B_taps),
            TensorAccessSequence.from_taps(C_taps),
        )

    return module


def main():
    argparser = argparse.ArgumentParser(
        prog="AIE whole-array fused matmul + bias (+ optional SiLU)",
        description="silu(A@B+bias) or A@B+bias across all columns, bf16 in/out, "
        "f32 accumulate, single xclbin",
    )
    argparser.add_argument("--dev", type=str, choices=["npu", "npu2"], default="npu2")
    argparser.add_argument("-M", type=int, default=512)
    argparser.add_argument("-K", type=int, default=768)
    argparser.add_argument("-N", type=int, default=3072)
    argparser.add_argument("-m", type=int, default=32)
    argparser.add_argument("-k", type=int, default=32)
    argparser.add_argument("-n", type=int, default=32)
    argparser.add_argument("--n-aie-cols", type=int, choices=[1, 2, 4, 8], default=8)
    argparser.add_argument("--b-col-maj", type=int, choices=[0, 1], default=0)
    argparser.add_argument(
        "--no-silu",
        action="store_true",
        help="bias mode: out = A@B+bias (plain f32->bf16 narrow, no activation). "
        "Default is silu mode: out = silu(A@B+bias).",
    )
    argparser.add_argument(
        "--gelu",
        action="store_true",
        help="gelu mode: out = gelu(A@B+bias) (tanh approx). Folds the Whisper encoder FFN activation "
        "into the fc1 epilogue. Overrides --no-silu. rtp[0]=2.",
    )
    argparser.add_argument(
        "--emulate-bf16-mmul-with-bfp16", type=_str2bool, default=False
    )
    # Accepted for makefile-common compatibility; this design is fixed to
    # bf16 in / f32 accumulate / bf16 out.
    argparser.add_argument("--dtype_in", type=str, default="bf16", choices=["bf16"])
    argparser.add_argument(
        "--dtype_out", type=str, default="f32", choices=["f32", "bf16"]
    )
    argparser.add_argument("--trace_size", type=int, default=0)
    # Index into `workers`, not a tile coordinate. Row 2 (index 0) is the C-stream aggregation
    # point and has no free South port -- see the enable_trace comment for the per-width table.
    argparser.add_argument("--trace_worker", type=int, default=0)
    # Comma-separated CoreEvent names, PORT_* ones optionally bound as NAME:BUNDLE:CHANNEL:DIR
    # (see _trace_event); empty = the default eight.
    # AIE2 gives 8 trace events per core, so this is a CHOICE, not a filter: the default set
    # (vector issue + the three stalls + two DMA ports) accounts for 33.05% of the traced span
    # at cols=4, leaving 66.95% dark purely because no scalar/load-store event is in it.
    argparser.add_argument("--trace_events", type=str, default="")
    # Trace the memtile that PRODUCES B_L2L1_<j> -- i.e. the B feed for AIE row j+2. -1 = off.
    # Additive: the core trace stays on, so one run carries both ends of the same feed.
    argparser.add_argument("--trace_memtile", type=int, default=-1)
    # Comma-separated MemTileEvent names, PORT_* ones bound as NAME:BUNDLE:CHANNEL:DIR.
    argparser.add_argument("--trace_memtile_events", type=str, default="")
    argparser.add_argument("--generate-taps", action="store_true")
    argparser.add_argument(
        "--c-panel-width",
        type=int,
        default=0,
        help="drain C panel-major as [N/W, M, W] instead of row-major [M, N] (0 = off). "
        "Must equal n_aie_cols*n. Lets a K-split consumer take each panel as a contiguous "
        "device sub-buffer, deleting the separate deinterleave dispatch. Insts-only: the "
        "xclbin is byte-identical to the row-major build.",
    )
    argparser.add_argument(
        "--glu",
        action="store_true",
        help="glu mode: out = a * sigmoid(g) over the tile's [value|gate] halves (rtp[0]=3). Folds the "
        "conv-module GLU into pw1's epilogue. REQUIRES W1's columns permuted at weight load so each "
        "tile holds 64 value columns and their 64 gate partners; without that the pairing is wrong and "
        "silently so. Overrides --gelu/--no-silu. Drain stays full width by design.",
    )
    argparser.add_argument(
        "--a-panel-width",
        type=int,
        default=0,
        help="read A from a [K//W, M, W] panel-major buffer instead of row-major [M, K] "
        "(0 = off). The mirror of --c-panel-width, for consuming a producer that already "
        "drained panel-major. Insts-only. Requires N//n//n_aie_cols == 1, since the panel "
        "index spends the A TAP's outer repeat dimension.",
    )
    argparser.add_argument(
        "--k-loop-rtp",
        action="store_true",
        help="k-loop-bound-as-rtp PoC: drive the core's K-tile loop bound from rtp[1] "
        "(a runtime memref.load) instead of baking K//k as a compile-time constant. "
        "Claim under test: the xclbin/core-ELF becomes independent of K, so only the "
        "insts stream (A/B tap counts + the rtp[1] write) needs to vary per K value.",
    )
    argparser.add_argument(
        "--mode-resadd",
        action="store_true",
        help="add resadd as MODE 4 of this xclbin, reusing the GEMM's own A/B input channels "
        "and C drain instead of declaring a second topology. A second topology cannot route: "
        "the GEMM already holds core DMA 2/2, East/South/West 4/4 and memtile DMA 6/6, and two "
        "fifos in one excl_group still cost two channels. rtp[0]=4 runs resadd, 0-3 keep the "
        "GEMM epilogues.",
    )
    argparser.add_argument(
        "--rtp-mode-resadd",
        action="store_true",
        help="bake rtp[0]=4 into THIS instruction stream, selecting the resadd mode. Needs "
        "--mode-resadd (which puts the body in the xclbin). The two streams share one xclbin.",
    )
    argparser.add_argument(
        "--resadd-only",
        action="store_true",
        help="build the resadd body ALONE -- same shapes, same borrowed topology, same stream "
        "contract, but no matmul in the core ELF. Discriminator for the mode-4 hang: completes "
        "=> the fault is two-body co-residency, hangs => the operator is implicated.",
    )
    argparser.add_argument(
        "--mode-read-late",
        action="store_true",
        help="peel the first A/B pair so the mode-4 branch reads rtp[0] AFTER an objectFIFO "
        "acquire instead of at the top of the tile. Needs --mode-resadd. Tests the measured "
        "one-tile rtp visibility lag: the top-of-tile read samples the previous dispatch's "
        "mode, so each core's first tile after a mode change runs the wrong body.",
    )
    argparser.add_argument(
        "--k-read-late",
        action="store_true",
        help="peel the first A/B pair so the k-loop trip count is read from rtp[1] AFTER an "
        "objectFIFO acquire instead of at the top of the tile. Needs --k-loop-rtp. Fixes the "
        "measured mixed-K unsoundness: two streams with different K on ONE hardware context "
        "corrupt each other because the top-of-tile read samples whichever dispatch happened "
        "to enter the body.",
    )
    argparser.add_argument(
        "--mode-lnaffcast",
        type=int,
        default=0,
        metavar="COLS",
        help="put the lnaffcast body (LN + affine + f32->bf16 cast) in the xclbin, over rows of "
        "COLS columns. BF16-OUT ONLY, the mirror of --mode-resadd's f32-out constraint: it "
        "stages into the per-core cacc and writes the C tile once, and neither exists on the "
        "f32-out path. Declares nothing -- one x row is two A tiles, gb is one B tile, and a C "
        "tile holds m*n/COLS output rows, which is exactly cacc.",
    )
    argparser.add_argument(
        "--rtp-mode-lnaffcast",
        action="store_true",
        help="bake rtp[0]=18 into THIS instruction stream, selecting the lnaffcast mode. Needs "
        "--mode-lnaffcast (which puts the body in the xclbin). The two streams share one xclbin.",
    )
    argparser.add_argument(
        "--lnaffcast-rows",
        type=int,
        default=0,
        metavar="ROWS",
        help="x rows one lnaffcast dispatch covers. Default: the most the declared A and C "
        "tensors hold, rounded down to a whole round.",
    )
    argparser.add_argument(
        "--lnaffcast-group-rounds",
        type=int,
        default=1,
        metavar="R",
        help="rounds per TaskGroup. tg.finish() is a host-side await, so 1 serialises the whole "
        "sequence at every round boundary; larger lets the DMA queue run ahead.",
    )
    argparser.add_argument(
        "--lnaffcast-c-fanout",
        action="store_true",
        help="give each of the n_aie_cols columns its own output region instead of writing them "
        "all to one. The columns of an array row share an A fifo and so compute the SAME rows; "
        "separating them lets a probe check the copies agree. Costs n_aie_cols x the C tensor, "
        "so it divides the rows one dispatch covers by the same factor.",
    )
    argparser.add_argument(
        "--lnaffcast-contig-taps",
        type=str,
        default="",
        metavar="ABC",
        help="TIMING-ONLY control: give the named taps (subset of 'abc') contiguous strides at "
        "unchanged sizes, offset and footprint, so only the innermost run changes. The output "
        "is wrong by construction -- the real strides ARE the un-permute -- so an arm built "
        "with this can be compared on wall clock and nothing else.",
    )
    argparser.add_argument(
        "--lnaffcast-1x",
        action="store_true",
        help="swap the operands: x rides B (per column) and gb rides A (per row, broadcast). "
        "The columns of an array row share an A fifo, so x on A makes all n_aie_cols of them "
        "compute the same output rows -- 4 useful C tiles per round of 32. This route makes "
        "every core's output distinct, at the cost of a n_aie_rows-way skip on the B stream.",
    )
    argparser.add_argument(
        "--mode-resadd2a",
        action="store_true",
        help="put `out = a + scale*b` in the xclbin with BOTH operands on the A fifo. F32-OUT "
        "ONLY: the C tile is the staging buffer, `a` widened into it and scale*b accumulated on "
        "top. resadd has no weight to absorb the A broadcast the way lnaffcast's gb does, so "
        "each core acquires every column's share and applies its own -- 2 * n/k tiles per C "
        "tile per column.",
    )
    argparser.add_argument(
        "--rtp-mode-resadd2a",
        action="store_true",
        help="bake rtp[0]=5 into THIS instruction stream, selecting the both-on-A resadd mode. "
        "Needs --mode-resadd2a (which puts the body in the xclbin).",
    )
    argparser.add_argument(
        "--resadd2a-rows",
        type=int,
        default=0,
        help="output rows the mode's stream covers (0 = what the A tensor holds as two "
        "N-wide operands). Insts-only, so several row counts share one xclbin.",
    )
    argparser.add_argument(
        "--resadd2a-rev-rows",
        action="store_true",
        help="fill the array rows far-end-first. Insts-only, so it shares an xclbin with the "
        "forward arm: it separates a fill-order effect from a routing/service-order one when a "
        "hung dispatch drains a prefix of the rows.",
    )
    argparser.add_argument(
        "--resadd2a-scale",
        type=float,
        default=1.0,
        help="the scale in `a + scale*b` (1.0 = full residual, 0.5 = Macaron). Travels as its "
        "f32 bit pattern in rtp[2], so it costs no input channel and one build serves both "
        "encoder resadd bricks.",
    )
    args = argparser.parse_args()
    maybe_module = my_matmul(
        args.dev,
        args.M,
        args.K,
        args.N,
        args.m,
        args.k,
        args.n,
        args.n_aie_cols,
        args.b_col_maj,
        not args.no_silu,
        args.emulate_bf16_mmul_with_bfp16,
        args.trace_size,
        args.generate_taps,
        args.gelu,
        args.glu,
        args.c_panel_width,
        args.dtype_out,
        args.k_loop_rtp,
        args.a_panel_width,
        args.trace_worker,
        args.trace_events,
        args.trace_memtile,
        args.trace_memtile_events,
        args.mode_resadd,
        args.rtp_mode_resadd,
        args.resadd_only,
        args.mode_read_late,
        args.k_read_late,
        args.mode_lnaffcast,
        args.rtp_mode_lnaffcast,
        args.lnaffcast_rows,
        args.lnaffcast_c_fanout,
        args.lnaffcast_group_rounds,
        args.lnaffcast_contig_taps,
        args.lnaffcast_1x,
        args.mode_resadd2a,
        args.rtp_mode_resadd2a,
        args.resadd2a_rows,
        args.resadd2a_scale,
        args.resadd2a_rev_rows,
    )
    if args.generate_taps:
        return maybe_module
    else:
        print(maybe_module)


if __name__ == "__main__":
    main()
