#!/usr/bin/env python3
"""GATE: the committed rope_lut_tables.inc is still what its generator produces.

`rope_lut_tables.inc` is generated by `../rope-lut/gen_rope_lut_tables.py` under a MEASURED
`aie::lut<4,bfloat16>` placement rule, and it is committed. Nothing ran the generator afterwards, so a
hand-edit to the .inc -- or a change to the placement rule that was not regenerated -- would sit in the
tree indefinitely and only surface as wrong rope numerics on device.

The generator already grew a `--check` mode that regenerates in memory and byte-compares. This wires
that mode into the drain so a drift FAILS rather than merely being checkable. Device-free.

Script-style (no `do_*()`), so it belongs in `drain_device.py`'s SCRIPT_TARGETS, which runs it as
`sys.executable -u verify_rope_lut_tables_repro.py` and scores it on exit status.
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
GEN = HERE.parent / "rope-lut" / "gen_rope_lut_tables.py"


def main():
    if not GEN.exists():
        print(f"FAIL generator missing: {GEN}")
        return 1
    # Run with THIS interpreter: the generator needs ml_dtypes, which several probes in this
    # directory already require, so the drain's interpreter is the right one. Invoking a different
    # python here would let the gate pass under an env the rest of the drain never uses.
    p = subprocess.run([sys.executable, "-u", str(GEN), "--check"],
                       capture_output=True, text=True)
    sys.stdout.write(p.stdout)
    sys.stderr.write(p.stderr)
    if p.returncode != 0:
        print("FAIL rope_lut_tables.inc reproducibility -- regenerate with "
              f"`{sys.executable} {GEN}` or explain the drift")
        return 1
    print("PASS rope_lut_tables.inc reproduces byte-for-byte from its generator")
    return 0


if __name__ == "__main__":
    sys.exit(main())
