#ifndef XDNA_SR_H
#define XDNA_SR_H

/* Generated by cbindgen from npu-sr-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque SR engine handle.
 */
typedef struct XdnaSr XdnaSr;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 1 if an NPU device is present, else 0.
 */
int xdna_sr_available(void);

/**
 * Load a schedule (path to `<net>.json`). `use_npu`!=0 uses the NPU frontier. NULL on error
 * (see `xdna_sr_last_error`).
 */
struct XdnaSr *xdna_sr_create(const char *schedule_path, int use_npu);

/**
 * The integer scale factor of the loaded net (e.g. 3), or -1 on error.
 */
int xdna_sr_scale(const struct XdnaSr *h);

/**
 * Upscale one interleaved RGB8 frame. `out_rgb` must hold at least (w*scale)*(h*scale)*3 bytes.
 * Returns 0 on success (writing out_w/out_h if non-null), <0 on error.
 */
int xdna_sr_process_rgb8(struct XdnaSr *h,
                         const uint8_t *in_rgb,
                         uintptr_t w,
                         uintptr_t height,
                         uint8_t *out_rgb,
                         uintptr_t out_cap,
                         uintptr_t *out_w,
                         uintptr_t *out_h);

/**
 * Free an engine handle.
 */
void xdna_sr_free(struct XdnaSr *h);

/**
 * Thread-local last error message (empty string if none). Pointer valid until the next call on this thread.
 */
const char *xdna_sr_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XDNA_SR_H */
