#ifndef XDNA_SR_H
#define XDNA_SR_H

/* Generated by cbindgen from npu-sr-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque SR engine handle.
 */
typedef struct XdnaSr XdnaSr;

/**
 * Padded-frame geometry a `layout: "frame"` fsr1 backend expects, for a zero-copy dma-buf caller
 * that builds its own buffers. See [`xdna_sr_frame_layout`].
 */
typedef struct XdnaSrFrameLayout {
  uintptr_t in_w;
  uintptr_t in_h;
  uintptr_t in_pad_w;
  uintptr_t in_pad_h;
  uintptr_t in_pad_x;
  uintptr_t in_pad_y;
  uintptr_t out_pad_w;
  uintptr_t out_pad_h;
  uintptr_t scale;
} XdnaSrFrameLayout;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 1 if an NPU device is present, else 0.
 */
int xdna_sr_available(void);

/**
 * Load a schedule (path to `<net>.json`). `use_npu`!=0 uses the NPU frontier. NULL on error
 * (see `xdna_sr_last_error`).
 */
struct XdnaSr *xdna_sr_create(const char *schedule_path, int use_npu);

/**
 * The integer scale factor of the loaded net (e.g. 3), or -1 on error.
 */
int xdna_sr_scale(const struct XdnaSr *h);

/**
 * Upscale one interleaved RGB8 frame. `out_rgb` must hold at least (w*scale)*(h*scale)*3 bytes.
 * Returns 0 on success (writing out_w/out_h if non-null), <0 on error.
 */
int xdna_sr_process_rgb8(struct XdnaSr *h,
                         const uint8_t *in_rgb,
                         uintptr_t w,
                         uintptr_t height,
                         uint8_t *out_rgb,
                         uintptr_t out_cap,
                         uintptr_t *out_w,
                         uintptr_t *out_h);

/**
 * Upscale one BGRA8 frame (DRM ARGB8888 byte order: B, G, R, A in memory). Rows are `in_stride`
 * / `out_stride` bytes apart; `out_rgba` holds at least (h*scale-1)*out_stride + w*scale*4 bytes
 * (`out_cap`). Output alpha is 0xff. Returns 0 on success (writing out_w/out_h if non-null).
 */
int xdna_sr_process_bgra8(struct XdnaSr *h,
                          const uint8_t *in_bgra,
                          uintptr_t w,
                          uintptr_t height,
                          uintptr_t in_stride,
                          uint8_t *out_bgra,
                          uintptr_t out_stride,
                          uintptr_t out_cap,
                          uintptr_t *out_w,
                          uintptr_t *out_h);

/**
 * Fills `*out` with the loaded backend's padded-frame geometry and returns 0 if it takes padded
 * BGRA frames (fsr1 frame layout); <0 (e.g. a conv-net or tiled-fsr1 schedule) otherwise.
 */
int xdna_sr_frame_layout(const struct XdnaSr *h, struct XdnaSrFrameLayout *out);

/**
 * Zero-copy dispatch: `in_fd`/`out_fd` are dma-buf fds of BGRA8 buffers laid out per
 * `xdna_sr_frame_layout` (in: producer-filled INCLUDING the edge-replicated padding; out: the full
 * padded output). Imports and caches each fd (by the dma-buf's inode). Blocking: returns after the
 * NPU finished. `*out_fence_fd` is set to -1 (reserved for an async version). <0 on error.
 */
int xdna_sr_process_dmabuf(struct XdnaSr *h, int in_fd, int out_fd, int *out_fence_fd);

/**
 * Free an engine handle.
 */
void xdna_sr_free(struct XdnaSr *h);

/**
 * Thread-local last error message (empty string if none). Pointer valid until the next call on this thread.
 */
const char *xdna_sr_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XDNA_SR_H */
