#ifndef XDNA_SR_H
#define XDNA_SR_H

/* Generated by cbindgen from npu-sr-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque SR engine handle.
 */
typedef struct XdnaSr XdnaSr;

/**
 * Padded-frame geometry of an FSR1 Y engine at any scale, for a zero-copy dma-buf caller. The
 * input plane is in_pad_w x in_pad_h bytes with the frame at (in_pad_x, in_pad_y), the rest
 * edge-replicated by the producer; the output plane is out_pad_w x out_pad_h bytes with the valid
 * out_w x out_h at its top left. 1 byte per pixel (the NV12 Y plane). Scale is scale_num/scale_den.
 */
typedef struct XdnaSrLayout {
  uintptr_t in_w;
  uintptr_t in_h;
  uintptr_t out_w;
  uintptr_t out_h;
  uintptr_t in_pad_w;
  uintptr_t in_pad_h;
  uintptr_t in_pad_x;
  uintptr_t in_pad_y;
  uintptr_t out_pad_w;
  uintptr_t out_pad_h;
  uintptr_t scale_num;
  uintptr_t scale_den;
} XdnaSrLayout;

/**
 * Padded-frame geometry a `layout: "frame"` fsr1 backend expects, for a zero-copy dma-buf caller
 * that builds its own buffers. See [`xdna_sr_frame_layout`].
 */
typedef struct XdnaSrFrameLayout {
  uintptr_t in_w;
  uintptr_t in_h;
  uintptr_t in_pad_w;
  uintptr_t in_pad_h;
  uintptr_t in_pad_x;
  uintptr_t in_pad_y;
  uintptr_t out_pad_w;
  uintptr_t out_pad_h;
  uintptr_t scale;
} XdnaSrFrameLayout;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 1 if an NPU device is present, else 0.
 */
int xdna_sr_available(void);

/**
 * Load a schedule (path to `<net>.json`). `use_npu`!=0 uses the NPU frontier. NULL on error
 * (see `xdna_sr_last_error`).
 */
struct XdnaSr *xdna_sr_create(const char *schedule_path, int use_npu);

/**
 * 1 if FSR1 has a scale for `in` -> `out` (1, 3/2, 5/3, 2 or 3, each axis within a source
 * pixel), writing it to *num / *den if non-null; else 0. No device needed.
 */
int xdna_sr_fsr1_scale(uintptr_t in_w,
                       uintptr_t in_h,
                       uintptr_t out_w,
                       uintptr_t out_h,
                       uintptr_t *num,
                       uintptr_t *den);

/**
 * FSR1 on the NV12 Y plane for `in` -> `out` from the one-design export (`export_path`: its
 * fsr1_rt.json or the directory holding it); the scale comes from the sizes (see
 * `xdna_sr_fsr1_scale`). `sharpness`: RCAS in stops, 0 the sharpest. Query the buffers with
 * `xdna_sr_layout`, dispatch with `xdna_sr_process_dmabuf`, change shape with
 * `xdna_sr_configure`. NULL on error (an unsupported scale included; see `xdna_sr_last_error`).
 */
struct XdnaSr *xdna_sr_create_fsr1(const char *export_path,
                                   uintptr_t in_w,
                                   uintptr_t in_h,
                                   uintptr_t out_w,
                                   uintptr_t out_h,
                                   float sharpness);

/**
 * Switch an `xdna_sr_create_fsr1` engine to another frame shape (any supported scale and size)
 * and sharpness without reloading the design. The layout changes: query it again. 0, or <0 on
 * error (the engine keeps its previous shape).
 */
int xdna_sr_configure(struct XdnaSr *h,
                      uintptr_t in_w,
                      uintptr_t in_h,
                      uintptr_t out_w,
                      uintptr_t out_h,
                      float sharpness);

/**
 * Fills `*out` for an `xdna_sr_create_fsr1` engine (any scale) or a frame-layout schedule
 * (integer scale); 0, or <0 for other backends.
 */
int xdna_sr_layout(const struct XdnaSr *h, struct XdnaSrLayout *out);

/**
 * The integer scale factor of the loaded net (e.g. 3), 0 for an FSR1 engine at a scale with no
 * integer form (3/2, 5/3: see `xdna_sr_layout`), or -1 on error.
 */
int xdna_sr_scale(const struct XdnaSr *h);

/**
 * Upscale one interleaved RGB8 frame. `out_rgb` must hold at least (w*scale)*(h*scale)*3 bytes.
 * Returns 0 on success (writing out_w/out_h if non-null), <0 on error.
 */
int xdna_sr_process_rgb8(struct XdnaSr *h,
                         const uint8_t *in_rgb,
                         uintptr_t w,
                         uintptr_t height,
                         uint8_t *out_rgb,
                         uintptr_t out_cap,
                         uintptr_t *out_w,
                         uintptr_t *out_h);

/**
 * Upscale one BGRA8 frame (DRM ARGB8888 byte order: B, G, R, A in memory). Rows are `in_stride`
 * / `out_stride` bytes apart; `out_rgba` holds at least (h*scale-1)*out_stride + w*scale*4 bytes
 * (`out_cap`). Output alpha is 0xff. Returns 0 on success (writing out_w/out_h if non-null).
 */
int xdna_sr_process_bgra8(struct XdnaSr *h,
                          const uint8_t *in_bgra,
                          uintptr_t w,
                          uintptr_t height,
                          uintptr_t in_stride,
                          uint8_t *out_bgra,
                          uintptr_t out_stride,
                          uintptr_t out_cap,
                          uintptr_t *out_w,
                          uintptr_t *out_h);

/**
 * Fills `*out` with the loaded backend's padded-frame geometry and returns 0 if it takes padded
 * BGRA frames (fsr1 frame layout); <0 (e.g. a conv-net or tiled-fsr1 schedule) otherwise.
 */
int xdna_sr_frame_layout(const struct XdnaSr *h, struct XdnaSrFrameLayout *out);

/**
 * Zero-copy dispatch: `in_fd`/`out_fd` are dma-buf fds of BGRA8 buffers laid out per
 * Bytes per pixel of the frame layout's planes: 4 for BGRA, 1 for the NV12 Y plane (the caller
 * fills the chroma plane of its output buffer itself). <0 without a frame-layout backend.
 */
int xdna_sr_frame_bytes_per_px(const struct XdnaSr *h);

/**
 * `xdna_sr_frame_layout` (in: producer-filled INCLUDING the edge-replicated padding; out: the full
 * padded output). Imports and caches each fd (by the dma-buf's inode). Blocking: returns after the
 * NPU finished. `*out_fence_fd` is set to -1 (reserved for an async version). <0 on error.
 */
int xdna_sr_process_dmabuf(struct XdnaSr *h, int in_fd, int out_fd, int *out_fence_fd);

/**
 * Free an engine handle.
 */
void xdna_sr_free(struct XdnaSr *h);

/**
 * Thread-local last error message (empty string if none). Pointer valid until the next call on this thread.
 */
const char *xdna_sr_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XDNA_SR_H */
