#!/usr/bin/env bash
# setup_worktree.sh -- make a worktree usable without copying anything big into it:
# link the shared artifact store, and put Cargo's build output on the data disk.
#
#   scripts/setup_worktree.sh          # this worktree
#
# Idempotent. Run it once per new worktree, and again after adding a store entry.
#
# Anchors, overridable in the env, mirroring cache_env.sh:
#   XDNA_ARTIFACT_STORE  weights/goldens/refs shared by every worktree
#   XDNA_MODEL_STORE     the models/ tree
#   XDNA_BUILD_ROOT      parent of the per-worktree Cargo target dirs
#
# The target dir is PER-WORKTREE and not shared: cargo takes an exclusive lock on it,
# so two worktrees building at once would serialize, and worktrees whose sources differ
# evict each other's fingerprints for the workspace-local crates. Reuse ACROSS worktrees
# is sccache's job (rustc-wrapper in ~/.cargo/config.toml), which needs neither.
set -euo pipefail

store="${XDNA_ARTIFACT_STORE:-/mnt/data/xdna/artifacts}"
models="${XDNA_MODEL_STORE:-/mnt/data/xdna/models}"
build_root="${XDNA_BUILD_ROOT:-/mnt/data/xdna/build}"

root="$(git rev-parse --show-toplevel)"
name="$(basename "$root")"
cd "$root"

link_into() {  # link_into <target> <link-path>
  local tgt="$1" link="$2"
  [ -e "$tgt" ] || return 0
  if [ -L "$link" ]; then
    [ "$(readlink "$link")" = "$tgt" ] || ln -sfn "$tgt" "$link"
  elif [ -e "$link" ]; then
    echo "  skip $link -- a real path is here, not a link (move it to the store first)" >&2
  else
    ln -sn "$tgt" "$link"
  fi
}

mkdir -p artifacts
for entry in "$store"/*; do
  [ -e "$entry" ] || continue
  # An artifact whose validity is established by its POSITION cannot be relocated: moving it
  # moves its gate. artifact.rs walks UP from the decode dir for toolchain.lock, so with no dev
  # checkout above it the freshness check drops from Stale (hard error, "rebuild") to
  # Unverifiable (warn) and a stale artifact loads silently. The property is the stamp, not the
  # directory name -- meta.json's `toolchain.hash`, which is what check_toolchain_freshness reads.
  # NB: test the grep OUTPUT, not find's exit status -- find succeeds whether or not grep matched.
  if find "$entry" -maxdepth 3 -name meta.json -exec grep -l '"toolchain"' {} + 2>/dev/null | grep -q .; then
    echo "  skip $(basename "$entry") -- toolchain-stamped build output; it stays in the checkout" >&2
    continue
  fi
  link_into "$entry" "artifacts/$(basename "$entry")"
done
link_into "$models" models

target_dir="$build_root/$name/target"
mkdir -p "$target_dir" "$root/.cargo"
cat > "$root/.cargo/config.toml" <<CARGO
# Generated by scripts/setup_worktree.sh -- untracked, per-worktree.
# Cargo merges this with rust/.cargo/config.toml; that one owns rustflags, this one
# only moves the output off the root volume.
[build]
target-dir = "$target_dir"
CARGO

echo "$name: artifacts linked to $store, target-dir $target_dir"
