#ifndef NPU_ENGINE_H
#define NPU_ENGINE_H

/* Generated by cbindgen from npu-capi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque model handle.
 */
typedef struct NpuModel NpuModel;

/**
 * Opaque control-plane handle: a running device actor + its config path.
 */
typedef struct NpuRuntime NpuRuntime;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 1 if an NPU device is present, else 0.
 */
int npu_available(void);

/**
 * Load a model from a scenario TOML path. Returns NULL on error (see `npu_last_error`).
 */
struct NpuModel *npu_model_load(const char *scenario_path);

/**
 * 0 = asr, 1 = embed, -1 = error.
 */
int npu_model_kind(const struct NpuModel *m);

/**
 * ASR: PCM i16 mono -> malloc'd UTF-8 C string (free with `npu_string_free`). NULL on error.
 */
char *npu_transcribe(struct NpuModel *m, const int16_t *pcm, uintptr_t n, uint32_t sample_rate);

/**
 * Embedding. Call with out_cap==0 (or out==NULL) to get the dimension; call again with a buffer of
 * at least that many floats to fill it. Returns the dimension, or -1 on error.
 */
int npu_embed(struct NpuModel *m, const char *text, float *out, uintptr_t out_cap);

/**
 * Free a string returned by `npu_transcribe`.
 */
void npu_string_free(char *s);

/**
 * Free a model handle.
 */
void npu_model_free(struct NpuModel *m);

/**
 * Thread-local last error message (empty string if none). Pointer valid until the next call on
 * this thread.
 */
const char *npu_last_error(void);

/**
 * Start the control plane from a config TOML path (reconciles its models). NULL on error.
 */
struct NpuRuntime *npu_runtime_start(const char *config_path);

/**
 * ASR through the control plane (model name or NULL for the configured default). Caller frees.
 */
char *npu_runtime_transcribe(struct NpuRuntime *rt,
                             const char *model,
                             const int16_t *pcm,
                             uintptr_t n,
                             uint32_t sample_rate);

/**
 * Embedding through the control plane. Pass a buffer; returns the embedding length (>= written), or -1.
 */
int npu_runtime_embed(struct NpuRuntime *rt,
                      const char *model,
                      const char *text,
                      float *out,
                      uintptr_t out_cap);

/**
 * Re-read the config file and reconcile. Returns 0 on success, -1 on error.
 */
int npu_runtime_reload(struct NpuRuntime *rt);

/**
 * Model statuses as a JSON list (malloc'd; free with npu_string_free). NULL on error.
 */
char *npu_runtime_models_json(struct NpuRuntime *rt);

/**
 * Stop the control plane and free the handle.
 */
void npu_runtime_stop(struct NpuRuntime *rt);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NPU_ENGINE_H */
