##===- Makefile.cast -----------------------------------------------------===##
#
# Device-side f32 -> bf16 cast xclbin (resident-rails seam primitive). Modeled on
# Makefile.ctxln. Build (run from the ml/layernorm sandbox dir, via build_kernels):
#   make -f Makefile.cast NPU2=1 rows=512 cols=1024 build/final_cast_512x1024.xclbin
# Produces final_cast_${rows}x${cols}.xclbin + insts_cast_${rows}x${cols}.txt.
#
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../makefile-common
VPATH := ${srcdir}/../../../aie_kernels/aie2p

devicename ?= $(if $(filter 1,$(NPU2)),npu2,npu)
partcols ?=
partflag = $(if ${partcols},-p ${partcols},)
partsuf  = $(if ${partcols},_p${partcols}c,)
rows ?= 512
cols ?= 1024
tag = cast_${rows}x${cols}${partsuf}

aie_py_src = cast_f32_bf16_iron.py

all: build/final_${tag}.xclbin

build/cast_f32_bf16.o: cast_f32_bf16.cc
	mkdir -p ${@D}
	cd ${@D} && ${PEANO_INSTALL_DIR}/bin/clang++ ${PEANOWRAP2P_FLAGS} -c $< -o ${@F}

build/aie_${tag}.mlir: ${srcdir}/${aie_py_src}
	mkdir -p ${@D}
	python3 $< -d ${devicename} -r ${rows} -c ${cols} -t 0 ${partflag} > $@

build/final_${tag}.xclbin: build/aie_${tag}.mlir build/cast_f32_bf16.o
	mkdir -p ${@D}
	cd ${@D} && aiecc --get-xclbin --get-npu-insts \
		--peano ${PEANO_INSTALL_DIR} \
		--xclbin-name=${@F} --npu-insts-name=insts_${tag}.txt aie_${tag}.mlir
