##===- Makefile.affinecast -----------------------------------------------===##
#
# Device-side affine + f32->bf16 cast xclbin (resident-rails LN affine seam). Build:
#   make -f Makefile.affinecast NPU2=1 rows=512 cols=1024 build/final_affcast_512x1024.xclbin
# Produces final_affcast_${rows}x${cols}.xclbin + insts_affcast_${rows}x${cols}.txt.
#
srcdir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
include ${srcdir}/../../makefile-common
VPATH := ${srcdir}/../../../aie_kernels/aie2p

devicename ?= $(if $(filter 1,$(NPU2)),npu2,npu)
# partcols=N restricts the PARTITION to N columns (default: full device). A brick that uses 2
# columns but claims 8 blocks co-residency, making every xclbin transition an array reprogram.
partcols ?=
partflag = $(if ${partcols},-p ${partcols},)
partsuf  = $(if ${partcols},_p${partcols}c,)
rows ?= 512
cols ?= 1024
tag = affcast_${rows}x${cols}${partsuf}

aie_py_src = affine_cast_iron.py

all: build/final_${tag}.xclbin

build/affine_cast.o: affine_cast.cc
	mkdir -p ${@D}
	cd ${@D} && ${PEANO_INSTALL_DIR}/bin/clang++ ${PEANOWRAP2P_FLAGS} -c $< -o ${@F}

build/aie_${tag}.mlir: ${srcdir}/${aie_py_src}
	mkdir -p ${@D}
	python3 $< -d ${devicename} -r ${rows} -c ${cols} -t 0 ${partflag} > $@

build/final_${tag}.xclbin: build/aie_${tag}.mlir build/affine_cast.o
	mkdir -p ${@D}
	cd ${@D} && aiecc --get-xclbin --get-npu-insts \
		--peano ${PEANO_INSTALL_DIR} \
		--xclbin-name=${@F} --npu-insts-name=insts_${tag}.txt aie_${tag}.mlir
